// Code generated by MockGen. DO NOT EDIT.
// Source: streamgate/pkg/service (interfaces: TokenBlacklist)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_token_blacklist.go -package=mocks streamgate/pkg/service TokenBlacklist
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockTokenBlacklist is a mock of TokenBlacklist interface.
type MockTokenBlacklist struct {
	ctrl     *gomock.Controller
	recorder *MockTokenBlacklistMockRecorder
	isgomock struct{}
}

// MockTokenBlacklistMockRecorder is the mock recorder for MockTokenBlacklist.
type MockTokenBlacklistMockRecorder struct {
	mock *MockTokenBlacklist
}

// NewMockTokenBlacklist creates a new mock instance.
func NewMockTokenBlacklist(ctrl *gomock.Controller) *MockTokenBlacklist {
	mock := &MockTokenBlacklist{ctrl: ctrl}
	mock.recorder = &MockTokenBlacklistMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenBlacklist) EXPECT() *MockTokenBlacklistMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockTokenBlacklist) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockTokenBlacklistMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockTokenBlacklist)(nil).Close))
}

// IsRevoked mocks base method.
func (m *MockTokenBlacklist) IsRevoked(ctx context.Context, jti string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsRevoked", ctx, jti)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsRevoked indicates an expected call of IsRevoked.
func (mr *MockTokenBlacklistMockRecorder) IsRevoked(ctx, jti any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsRevoked", reflect.TypeOf((*MockTokenBlacklist)(nil).IsRevoked), ctx, jti)
}

// Revoke mocks base method.
func (m *MockTokenBlacklist) Revoke(ctx context.Context, jti string, expiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, jti, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revoke indicates an expected call of Revoke.
func (mr *MockTokenBlacklistMockRecorder) Revoke(ctx, jti, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockTokenBlacklist)(nil).Revoke), ctx, jti, expiresAt)
}
