// Code generated by MockGen. DO NOT EDIT.
// Source: streamgate/pkg/service (interfaces: ChallengeStore)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_challenge_store.go -package=mocks streamgate/pkg/service ChallengeStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	service "streamgate/pkg/service"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockChallengeStore is a mock of ChallengeStore interface.
type MockChallengeStore struct {
	ctrl     *gomock.Controller
	recorder *MockChallengeStoreMockRecorder
	isgomock struct{}
}

// MockChallengeStoreMockRecorder is the mock recorder for MockChallengeStore.
type MockChallengeStoreMockRecorder struct {
	mock *MockChallengeStore
}

// NewMockChallengeStore creates a new mock instance.
func NewMockChallengeStore(ctrl *gomock.Controller) *MockChallengeStore {
	mock := &MockChallengeStore{ctrl: ctrl}
	mock.recorder = &MockChallengeStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChallengeStore) EXPECT() *MockChallengeStoreMockRecorder {
	return m.recorder
}

// GetChallenge mocks base method.
func (m *MockChallengeStore) GetChallenge(ctx context.Context, id string) (*service.WalletChallenge, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChallenge", ctx, id)
	ret0, _ := ret[0].(*service.WalletChallenge)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChallenge indicates an expected call of GetChallenge.
func (mr *MockChallengeStoreMockRecorder) GetChallenge(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChallenge", reflect.TypeOf((*MockChallengeStore)(nil).GetChallenge), ctx, id)
}

// MarkChallengeUsed mocks base method.
func (m *MockChallengeStore) MarkChallengeUsed(ctx context.Context, id string, usedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkChallengeUsed", ctx, id, usedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkChallengeUsed indicates an expected call of MarkChallengeUsed.
func (mr *MockChallengeStoreMockRecorder) MarkChallengeUsed(ctx, id, usedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkChallengeUsed", reflect.TypeOf((*MockChallengeStore)(nil).MarkChallengeUsed), ctx, id, usedAt)
}

// SaveChallenge mocks base method.
func (m *MockChallengeStore) SaveChallenge(ctx context.Context, challenge *service.WalletChallenge) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveChallenge", ctx, challenge)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveChallenge indicates an expected call of SaveChallenge.
func (mr *MockChallengeStoreMockRecorder) SaveChallenge(ctx, challenge any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveChallenge", reflect.TypeOf((*MockChallengeStore)(nil).SaveChallenge), ctx, challenge)
}
