// Code generated by MockGen. DO NOT EDIT.
// Source: streamgate/pkg/service (interfaces: WalletSignatureVerifier)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_wallet_sig_verifier.go -package=mocks streamgate/pkg/service WalletSignatureVerifier
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockWalletSignatureVerifier is a mock of WalletSignatureVerifier interface.
type MockWalletSignatureVerifier struct {
	ctrl     *gomock.Controller
	recorder *MockWalletSignatureVerifierMockRecorder
	isgomock struct{}
}

// MockWalletSignatureVerifierMockRecorder is the mock recorder for MockWalletSignatureVerifier.
type MockWalletSignatureVerifierMockRecorder struct {
	mock *MockWalletSignatureVerifier
}

// NewMockWalletSignatureVerifier creates a new mock instance.
func NewMockWalletSignatureVerifier(ctrl *gomock.Controller) *MockWalletSignatureVerifier {
	mock := &MockWalletSignatureVerifier{ctrl: ctrl}
	mock.recorder = &MockWalletSignatureVerifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWalletSignatureVerifier) EXPECT() *MockWalletSignatureVerifierMockRecorder {
	return m.recorder
}

// VerifySignature mocks base method.
func (m *MockWalletSignatureVerifier) VerifySignature(ctx context.Context, address, message, signature string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifySignature", ctx, address, message, signature)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifySignature indicates an expected call of VerifySignature.
func (mr *MockWalletSignatureVerifierMockRecorder) VerifySignature(ctx, address, message, signature any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifySignature", reflect.TypeOf((*MockWalletSignatureVerifier)(nil).VerifySignature), ctx, address, message, signature)
}
