version: "2"

run:
  timeout: 5m
  tests: false

linters:
  enable:
    - govet
    - ineffassign
    - misspell
  disable:
    - errcheck
    - staticcheck
    - unused

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
