# golangci-lint configuration (v1 format)

run:
  timeout: 5m
  tests: false
  skip-dirs:
    - test
    - tests

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - revive

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: error-naming
      - name: error-return
      - name: error-strings
      - name: errorf

issues:
  exclude-dirs:
    - vendor
    - .git
    - node_modules
    - test
    - tests
  exclude-files:
    - ".*_test\\.go$"
    - ".*_mock\\.go$"
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    
    - path: ".*\\.pb\\.go$"
      linters:
        - all
    
    - path: ".*_mock\\.go$"
      linters:
        - all

  max-issues-per-linter: 0
  max-same-issues: 0
