// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.1
// source: proto/v1/upload.proto

package uploadv1

import (
	_ "github.com/rtcdance/streamgate/pkg/api/v1/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	FileSize      int64                  `protobuf:"varint,3,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	MimeType      string                 `protobuf:"bytes,4,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Checksum      string                 `protobuf:"bytes,5,opt,name=checksum,proto3" json:"checksum,omitempty"`
	ChunkSize     int32                  `protobuf:"varint,6,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitUploadRequest) Reset() {
	*x = InitUploadRequest{}
	mi := &file_proto_v1_upload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitUploadRequest) ProtoMessage() {}

func (x *InitUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_upload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitUploadRequest.ProtoReflect.Descriptor instead.
func (*InitUploadRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_upload_proto_rawDescGZIP(), []int{0}
}

func (x *InitUploadRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *InitUploadRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *InitUploadRequest) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *InitUploadRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *InitUploadRequest) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *InitUploadRequest) GetChunkSize() int32 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *InitUploadRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type InitUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadId      string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	UploadUrls    []string               `protobuf:"bytes,2,rep,name=upload_urls,json=uploadUrls,proto3" json:"upload_urls,omitempty"`
	ChunkCount    int32                  `protobuf:"varint,3,opt,name=chunk_count,json=chunkCount,proto3" json:"chunk_count,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitUploadResponse) Reset() {
	*x = InitUploadResponse{}
	mi := &file_proto_v1_upload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitUploadResponse) ProtoMessage() {}

func (x *InitUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_upload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitUploadResponse.ProtoReflect.Descriptor instead.
func (*InitUploadResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_upload_proto_rawDescGZIP(), []int{1}
}

func (x *InitUploadResponse) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *InitUploadResponse) GetUploadUrls() []string {
	if x != nil {
		return x.UploadUrls
	}
	return nil
}

func (x *InitUploadResponse) GetChunkCount() int32 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

func (x *InitUploadResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type UploadPartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadId      string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	PartNumber    int32                  `protobuf:"varint,2,opt,name=part_number,json=partNumber,proto3" json:"part_number,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Checksum      string                 `protobuf:"bytes,4,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadPartRequest) Reset() {
	*x = UploadPartRequest{}
	mi := &file_proto_v1_upload_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadPartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadPartRequest) ProtoMessage() {}

func (x *UploadPartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_upload_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadPartRequest.ProtoReflect.Descriptor instead.
func (*UploadPartRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_upload_proto_rawDescGZIP(), []int{2}
}

func (x *UploadPartRequest) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *UploadPartRequest) GetPartNumber() int32 {
	if x != nil {
		return x.PartNumber
	}
	return 0
}

func (x *UploadPartRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadPartRequest) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

type UploadPartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Etag          string                 `protobuf:"bytes,2,opt,name=etag,proto3" json:"etag,omitempty"`
	BytesReceived int64                  `protobuf:"varint,3,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadPartResponse) Reset() {
	*x = UploadPartResponse{}
	mi := &file_proto_v1_upload_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadPartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadPartResponse) ProtoMessage() {}

func (x *UploadPartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_upload_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadPartResponse.ProtoReflect.Descriptor instead.
func (*UploadPartResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_upload_proto_rawDescGZIP(), []int{3}
}

func (x *UploadPartResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UploadPartResponse) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *UploadPartResponse) GetBytesReceived() int64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

type CompleteUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadId      string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	Parts         []*PartETag            `protobuf:"bytes,2,rep,name=parts,proto3" json:"parts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteUploadRequest) Reset() {
	*x = CompleteUploadRequest{}
	mi := &file_proto_v1_upload_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteUploadRequest) ProtoMessage() {}

func (x *CompleteUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_upload_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteUploadRequest.ProtoReflect.Descriptor instead.
func (*CompleteUploadRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_upload_proto_rawDescGZIP(), []int{4}
}

func (x *CompleteUploadRequest) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *CompleteUploadRequest) GetParts() []*PartETag {
	if x != nil {
		return x.Parts
	}
	return nil
}

type CompleteUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ContentId     string                 `protobuf:"bytes,2,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteUploadResponse) Reset() {
	*x = CompleteUploadResponse{}
	mi := &file_proto_v1_upload_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteUploadResponse) ProtoMessage() {}

func (x *CompleteUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_upload_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteUploadResponse.ProtoReflect.Descriptor instead.
func (*CompleteUploadResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_upload_proto_rawDescGZIP(), []int{5}
}

func (x *CompleteUploadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CompleteUploadResponse) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *CompleteUploadResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CompleteUploadResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type AbortUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadId      string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortUploadRequest) Reset() {
	*x = AbortUploadRequest{}
	mi := &file_proto_v1_upload_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortUploadRequest) ProtoMessage() {}

func (x *AbortUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_upload_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortUploadRequest.ProtoReflect.Descriptor instead.
func (*AbortUploadRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_upload_proto_rawDescGZIP(), []int{6}
}

func (x *AbortUploadRequest) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *AbortUploadRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type AbortUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortUploadResponse) Reset() {
	*x = AbortUploadResponse{}
	mi := &file_proto_v1_upload_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortUploadResponse) ProtoMessage() {}

func (x *AbortUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_upload_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortUploadResponse.ProtoReflect.Descriptor instead.
func (*AbortUploadResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_upload_proto_rawDescGZIP(), []int{7}
}

func (x *AbortUploadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetUploadStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadId      string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUploadStatusRequest) Reset() {
	*x = GetUploadStatusRequest{}
	mi := &file_proto_v1_upload_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUploadStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadStatusRequest) ProtoMessage() {}

func (x *GetUploadStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_upload_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadStatusRequest.ProtoReflect.Descriptor instead.
func (*GetUploadStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_upload_proto_rawDescGZIP(), []int{8}
}

func (x *GetUploadStatusRequest) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

type GetUploadStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadId      string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	PartsUploaded int32                  `protobuf:"varint,3,opt,name=parts_uploaded,json=partsUploaded,proto3" json:"parts_uploaded,omitempty"`
	TotalParts    int32                  `protobuf:"varint,4,opt,name=total_parts,json=totalParts,proto3" json:"total_parts,omitempty"`
	BytesUploaded int64                  `protobuf:"varint,5,opt,name=bytes_uploaded,json=bytesUploaded,proto3" json:"bytes_uploaded,omitempty"`
	TotalBytes    int64                  `protobuf:"varint,6,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	StartedAt     int64                  `protobuf:"varint,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUploadStatusResponse) Reset() {
	*x = GetUploadStatusResponse{}
	mi := &file_proto_v1_upload_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUploadStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadStatusResponse) ProtoMessage() {}

func (x *GetUploadStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_upload_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadStatusResponse.ProtoReflect.Descriptor instead.
func (*GetUploadStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_upload_proto_rawDescGZIP(), []int{9}
}

func (x *GetUploadStatusResponse) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *GetUploadStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetUploadStatusResponse) GetPartsUploaded() int32 {
	if x != nil {
		return x.PartsUploaded
	}
	return 0
}

func (x *GetUploadStatusResponse) GetTotalParts() int32 {
	if x != nil {
		return x.TotalParts
	}
	return 0
}

func (x *GetUploadStatusResponse) GetBytesUploaded() int64 {
	if x != nil {
		return x.BytesUploaded
	}
	return 0
}

func (x *GetUploadStatusResponse) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *GetUploadStatusResponse) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *GetUploadStatusResponse) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type PartETag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartNumber    int32                  `protobuf:"varint,1,opt,name=part_number,json=partNumber,proto3" json:"part_number,omitempty"`
	Etag          string                 `protobuf:"bytes,2,opt,name=etag,proto3" json:"etag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartETag) Reset() {
	*x = PartETag{}
	mi := &file_proto_v1_upload_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartETag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartETag) ProtoMessage() {}

func (x *PartETag) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_upload_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartETag.ProtoReflect.Descriptor instead.
func (*PartETag) Descriptor() ([]byte, []int) {
	return file_proto_v1_upload_proto_rawDescGZIP(), []int{10}
}

func (x *PartETag) GetPartNumber() int32 {
	if x != nil {
		return x.PartNumber
	}
	return 0
}

func (x *PartETag) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

var File_proto_v1_upload_proto protoreflect.FileDescriptor

const file_proto_v1_upload_proto_rawDesc = "" +
	"\n" +
	"\x15proto/v1/upload.proto\x12\tupload.v1\x1a\x15proto/v1/common.proto\"\xc2\x02\n" +
	"\x11InitUploadRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x1b\n" +
	"\tfile_size\x18\x03 \x01(\x03R\bfileSize\x12\x1b\n" +
	"\tmime_type\x18\x04 \x01(\tR\bmimeType\x12\x1a\n" +
	"\bchecksum\x18\x05 \x01(\tR\bchecksum\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x06 \x01(\x05R\tchunkSize\x12F\n" +
	"\bmetadata\x18\a \x03(\v2*.upload.v1.InitUploadRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x92\x01\n" +
	"\x12InitUploadResponse\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\x12\x1f\n" +
	"\vupload_urls\x18\x02 \x03(\tR\n" +
	"uploadUrls\x12\x1f\n" +
	"\vchunk_count\x18\x03 \x01(\x05R\n" +
	"chunkCount\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\x03R\texpiresAt\"\x81\x01\n" +
	"\x11UploadPartRequest\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\x12\x1f\n" +
	"\vpart_number\x18\x02 \x01(\x05R\n" +
	"partNumber\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x1a\n" +
	"\bchecksum\x18\x04 \x01(\tR\bchecksum\"i\n" +
	"\x12UploadPartResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04etag\x18\x02 \x01(\tR\x04etag\x12%\n" +
	"\x0ebytes_received\x18\x03 \x01(\x03R\rbytesReceived\"_\n" +
	"\x15CompleteUploadRequest\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\x12)\n" +
	"\x05parts\x18\x02 \x03(\v2\x13.upload.v1.PartETagR\x05parts\"w\n" +
	"\x16CompleteUploadResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"content_id\x18\x02 \x01(\tR\tcontentId\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\"I\n" +
	"\x12AbortUploadRequest\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"/\n" +
	"\x13AbortUploadResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"5\n" +
	"\x16GetUploadStatusRequest\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\"\x9c\x02\n" +
	"\x17GetUploadStatusResponse\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12%\n" +
	"\x0eparts_uploaded\x18\x03 \x01(\x05R\rpartsUploaded\x12\x1f\n" +
	"\vtotal_parts\x18\x04 \x01(\x05R\n" +
	"totalParts\x12%\n" +
	"\x0ebytes_uploaded\x18\x05 \x01(\x03R\rbytesUploaded\x12\x1f\n" +
	"\vtotal_bytes\x18\x06 \x01(\x03R\n" +
	"totalBytes\x12\x1d\n" +
	"\n" +
	"started_at\x18\a \x01(\x03R\tstartedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\x03R\tupdatedAt\"?\n" +
	"\bPartETag\x12\x1f\n" +
	"\vpart_number\x18\x01 \x01(\x05R\n" +
	"partNumber\x12\x12\n" +
	"\x04etag\x18\x02 \x01(\tR\x04etag2\xa6\x03\n" +
	"\rUploadService\x12I\n" +
	"\n" +
	"InitUpload\x12\x1c.upload.v1.InitUploadRequest\x1a\x1d.upload.v1.InitUploadResponse\x12K\n" +
	"\n" +
	"UploadPart\x12\x1c.upload.v1.UploadPartRequest\x1a\x1d.upload.v1.UploadPartResponse(\x01\x12U\n" +
	"\x0eCompleteUpload\x12 .upload.v1.CompleteUploadRequest\x1a!.upload.v1.CompleteUploadResponse\x12L\n" +
	"\vAbortUpload\x12\x1d.upload.v1.AbortUploadRequest\x1a\x1e.upload.v1.AbortUploadResponse\x12X\n" +
	"\x0fGetUploadStatus\x12!.upload.v1.GetUploadStatusRequest\x1a\".upload.v1.GetUploadStatusResponseB'Z%streamgate/pkg/api/v1/upload;uploadv1b\x06proto3"

var (
	file_proto_v1_upload_proto_rawDescOnce sync.Once
	file_proto_v1_upload_proto_rawDescData []byte
)

func file_proto_v1_upload_proto_rawDescGZIP() []byte {
	file_proto_v1_upload_proto_rawDescOnce.Do(func() {
		file_proto_v1_upload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_upload_proto_rawDesc), len(file_proto_v1_upload_proto_rawDesc)))
	})
	return file_proto_v1_upload_proto_rawDescData
}

var file_proto_v1_upload_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_v1_upload_proto_goTypes = []any{
	(*InitUploadRequest)(nil),       // 0: upload.v1.InitUploadRequest
	(*InitUploadResponse)(nil),      // 1: upload.v1.InitUploadResponse
	(*UploadPartRequest)(nil),       // 2: upload.v1.UploadPartRequest
	(*UploadPartResponse)(nil),      // 3: upload.v1.UploadPartResponse
	(*CompleteUploadRequest)(nil),   // 4: upload.v1.CompleteUploadRequest
	(*CompleteUploadResponse)(nil),  // 5: upload.v1.CompleteUploadResponse
	(*AbortUploadRequest)(nil),      // 6: upload.v1.AbortUploadRequest
	(*AbortUploadResponse)(nil),     // 7: upload.v1.AbortUploadResponse
	(*GetUploadStatusRequest)(nil),  // 8: upload.v1.GetUploadStatusRequest
	(*GetUploadStatusResponse)(nil), // 9: upload.v1.GetUploadStatusResponse
	(*PartETag)(nil),                // 10: upload.v1.PartETag
	nil,                             // 11: upload.v1.InitUploadRequest.MetadataEntry
}
var file_proto_v1_upload_proto_depIdxs = []int32{
	11, // 0: upload.v1.InitUploadRequest.metadata:type_name -> upload.v1.InitUploadRequest.MetadataEntry
	10, // 1: upload.v1.CompleteUploadRequest.parts:type_name -> upload.v1.PartETag
	0,  // 2: upload.v1.UploadService.InitUpload:input_type -> upload.v1.InitUploadRequest
	2,  // 3: upload.v1.UploadService.UploadPart:input_type -> upload.v1.UploadPartRequest
	4,  // 4: upload.v1.UploadService.CompleteUpload:input_type -> upload.v1.CompleteUploadRequest
	6,  // 5: upload.v1.UploadService.AbortUpload:input_type -> upload.v1.AbortUploadRequest
	8,  // 6: upload.v1.UploadService.GetUploadStatus:input_type -> upload.v1.GetUploadStatusRequest
	1,  // 7: upload.v1.UploadService.InitUpload:output_type -> upload.v1.InitUploadResponse
	3,  // 8: upload.v1.UploadService.UploadPart:output_type -> upload.v1.UploadPartResponse
	5,  // 9: upload.v1.UploadService.CompleteUpload:output_type -> upload.v1.CompleteUploadResponse
	7,  // 10: upload.v1.UploadService.AbortUpload:output_type -> upload.v1.AbortUploadResponse
	9,  // 11: upload.v1.UploadService.GetUploadStatus:output_type -> upload.v1.GetUploadStatusResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_v1_upload_proto_init() }
func file_proto_v1_upload_proto_init() {
	if File_proto_v1_upload_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_upload_proto_rawDesc), len(file_proto_v1_upload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_upload_proto_goTypes,
		DependencyIndexes: file_proto_v1_upload_proto_depIdxs,
		MessageInfos:      file_proto_v1_upload_proto_msgTypes,
	}.Build()
	File_proto_v1_upload_proto = out.File
	file_proto_v1_upload_proto_goTypes = nil
	file_proto_v1_upload_proto_depIdxs = nil
}
