// Code generated by MockGen. DO NOT EDIT.
// Source: streamgate/pkg/web3/event (interfaces: EventStore)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_event_store.go -package=mocks streamgate/pkg/web3/event EventStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	event "github.com/rtcdance/streamgate/pkg/web3/event"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEventStore is a mock of EventStore interface.
type MockEventStore struct {
	ctrl     *gomock.Controller
	recorder *MockEventStoreMockRecorder
	isgomock struct{}
}

// MockEventStoreMockRecorder is the mock recorder for MockEventStore.
type MockEventStoreMockRecorder struct {
	mock *MockEventStore
}

// NewMockEventStore creates a new mock instance.
func NewMockEventStore(ctrl *gomock.Controller) *MockEventStore {
	mock := &MockEventStore{ctrl: ctrl}
	mock.recorder = &MockEventStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventStore) EXPECT() *MockEventStoreMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockEventStore) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockEventStoreMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockEventStore)(nil).Close))
}

// EventExists mocks base method.
func (m *MockEventStore) EventExists(eventID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EventExists", eventID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EventExists indicates an expected call of EventExists.
func (mr *MockEventStoreMockRecorder) EventExists(eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EventExists", reflect.TypeOf((*MockEventStore)(nil).EventExists), eventID)
}

// GetEventsByBlockRange mocks base method.
func (m *MockEventStore) GetEventsByBlockRange(fromBlock, toBlock uint64) ([]*event.IndexedEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventsByBlockRange", fromBlock, toBlock)
	ret0, _ := ret[0].([]*event.IndexedEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEventsByBlockRange indicates an expected call of GetEventsByBlockRange.
func (mr *MockEventStoreMockRecorder) GetEventsByBlockRange(fromBlock, toBlock any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventsByBlockRange", reflect.TypeOf((*MockEventStore)(nil).GetEventsByBlockRange), fromBlock, toBlock)
}

// LoadCheckpoint mocks base method.
func (m *MockEventStore) LoadCheckpoint(contractAddress string) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadCheckpoint", contractAddress)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadCheckpoint indicates an expected call of LoadCheckpoint.
func (mr *MockEventStoreMockRecorder) LoadCheckpoint(contractAddress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadCheckpoint", reflect.TypeOf((*MockEventStore)(nil).LoadCheckpoint), contractAddress)
}

// MarkEventsReorged mocks base method.
func (m *MockEventStore) MarkEventsReorged(blockHashes []string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkEventsReorged", blockHashes)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkEventsReorged indicates an expected call of MarkEventsReorged.
func (mr *MockEventStoreMockRecorder) MarkEventsReorged(blockHashes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkEventsReorged", reflect.TypeOf((*MockEventStore)(nil).MarkEventsReorged), blockHashes)
}

// SaveCheckpoint mocks base method.
func (m *MockEventStore) SaveCheckpoint(contractAddress string, blockNumber uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveCheckpoint", contractAddress, blockNumber)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveCheckpoint indicates an expected call of SaveCheckpoint.
func (mr *MockEventStoreMockRecorder) SaveCheckpoint(contractAddress, blockNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveCheckpoint", reflect.TypeOf((*MockEventStore)(nil).SaveCheckpoint), contractAddress, blockNumber)
}

// SaveEvent mocks base method.
func (m *MockEventStore) SaveEvent(event *event.IndexedEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveEvent", event)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveEvent indicates an expected call of SaveEvent.
func (mr *MockEventStoreMockRecorder) SaveEvent(event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveEvent", reflect.TypeOf((*MockEventStore)(nil).SaveEvent), event)
}
