// Code generated by MockGen. DO NOT EDIT.
// Source: streamgate/pkg/web3 (interfaces: FeeHistoryProvider)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_fee_history_provider.go -package=mocks streamgate/pkg/web3 FeeHistoryProvider
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	big "math/big"
	reflect "reflect"

	ethereum "github.com/ethereum/go-ethereum"
	gomock "go.uber.org/mock/gomock"
)

// MockFeeHistoryProvider is a mock of FeeHistoryProvider interface.
type MockFeeHistoryProvider struct {
	ctrl     *gomock.Controller
	recorder *MockFeeHistoryProviderMockRecorder
	isgomock struct{}
}

// MockFeeHistoryProviderMockRecorder is the mock recorder for MockFeeHistoryProvider.
type MockFeeHistoryProviderMockRecorder struct {
	mock *MockFeeHistoryProvider
}

// NewMockFeeHistoryProvider creates a new mock instance.
func NewMockFeeHistoryProvider(ctrl *gomock.Controller) *MockFeeHistoryProvider {
	mock := &MockFeeHistoryProvider{ctrl: ctrl}
	mock.recorder = &MockFeeHistoryProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeeHistoryProvider) EXPECT() *MockFeeHistoryProviderMockRecorder {
	return m.recorder
}

// FeeHistory mocks base method.
func (m *MockFeeHistoryProvider) FeeHistory(ctx context.Context, blockCount uint64, lastBlock *big.Int, rewardPercentiles []float64) (*ethereum.FeeHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FeeHistory", ctx, blockCount, lastBlock, rewardPercentiles)
	ret0, _ := ret[0].(*ethereum.FeeHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FeeHistory indicates an expected call of FeeHistory.
func (mr *MockFeeHistoryProviderMockRecorder) FeeHistory(ctx, blockCount, lastBlock, rewardPercentiles any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FeeHistory", reflect.TypeOf((*MockFeeHistoryProvider)(nil).FeeHistory), ctx, blockCount, lastBlock, rewardPercentiles)
}

// GetGasPrice mocks base method.
func (m *MockFeeHistoryProvider) GetGasPrice(ctx context.Context) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGasPrice", ctx)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGasPrice indicates an expected call of GetGasPrice.
func (mr *MockFeeHistoryProviderMockRecorder) GetGasPrice(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGasPrice", reflect.TypeOf((*MockFeeHistoryProvider)(nil).GetGasPrice), ctx)
}

// SuggestGasTipCap mocks base method.
func (m *MockFeeHistoryProvider) SuggestGasTipCap(ctx context.Context) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SuggestGasTipCap", ctx)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SuggestGasTipCap indicates an expected call of SuggestGasTipCap.
func (mr *MockFeeHistoryProviderMockRecorder) SuggestGasTipCap(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SuggestGasTipCap", reflect.TypeOf((*MockFeeHistoryProvider)(nil).SuggestGasTipCap), ctx)
}
