// Code generated by MockGen. DO NOT EDIT.
// Source: streamgate/pkg/web3 (interfaces: EthCaller)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_eth_caller.go -package=mocks streamgate/pkg/web3 EthCaller
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	big "math/big"
	reflect "reflect"

	ethereum "github.com/ethereum/go-ethereum"
	common "github.com/ethereum/go-ethereum/common"
	gomock "go.uber.org/mock/gomock"
)

// MockEthCaller is a mock of EthCaller interface.
type MockEthCaller struct {
	ctrl     *gomock.Controller
	recorder *MockEthCallerMockRecorder
	isgomock struct{}
}

// MockEthCallerMockRecorder is the mock recorder for MockEthCaller.
type MockEthCallerMockRecorder struct {
	mock *MockEthCaller
}

// NewMockEthCaller creates a new mock instance.
func NewMockEthCaller(ctrl *gomock.Controller) *MockEthCaller {
	mock := &MockEthCaller{ctrl: ctrl}
	mock.recorder = &MockEthCallerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEthCaller) EXPECT() *MockEthCallerMockRecorder {
	return m.recorder
}

// CallContract mocks base method.
func (m *MockEthCaller) CallContract(ctx context.Context, call ethereum.CallMsg, blockNumber *big.Int) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CallContract", ctx, call, blockNumber)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CallContract indicates an expected call of CallContract.
func (mr *MockEthCallerMockRecorder) CallContract(ctx, call, blockNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CallContract", reflect.TypeOf((*MockEthCaller)(nil).CallContract), ctx, call, blockNumber)
}

// CodeAt mocks base method.
func (m *MockEthCaller) CodeAt(ctx context.Context, contract common.Address, blockNumber *big.Int) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CodeAt", ctx, contract, blockNumber)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CodeAt indicates an expected call of CodeAt.
func (mr *MockEthCallerMockRecorder) CodeAt(ctx, contract, blockNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CodeAt", reflect.TypeOf((*MockEthCaller)(nil).CodeAt), ctx, contract, blockNumber)
}
