// Code generated by MockGen. DO NOT EDIT.
// Source: streamgate/pkg/web3 (interfaces: SignatureVerifierInterface)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_sig_verifier.go -package=mocks streamgate/pkg/web3 SignatureVerifierInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSignatureVerifierInterface is a mock of SignatureVerifierInterface interface.
type MockSignatureVerifierInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSignatureVerifierInterfaceMockRecorder
	isgomock struct{}
}

// MockSignatureVerifierInterfaceMockRecorder is the mock recorder for MockSignatureVerifierInterface.
type MockSignatureVerifierInterfaceMockRecorder struct {
	mock *MockSignatureVerifierInterface
}

// NewMockSignatureVerifierInterface creates a new mock instance.
func NewMockSignatureVerifierInterface(ctrl *gomock.Controller) *MockSignatureVerifierInterface {
	mock := &MockSignatureVerifierInterface{ctrl: ctrl}
	mock.recorder = &MockSignatureVerifierInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSignatureVerifierInterface) EXPECT() *MockSignatureVerifierInterfaceMockRecorder {
	return m.recorder
}

// VerifySignature mocks base method.
func (m *MockSignatureVerifierInterface) VerifySignature(ctx context.Context, address, message, signature string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifySignature", ctx, address, message, signature)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifySignature indicates an expected call of VerifySignature.
func (mr *MockSignatureVerifierInterfaceMockRecorder) VerifySignature(ctx, address, message, signature any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifySignature", reflect.TypeOf((*MockSignatureVerifierInterface)(nil).VerifySignature), ctx, address, message, signature)
}
