// Code generated by MockGen. DO NOT EDIT.
// Source: streamgate/pkg/web3/solana (interfaces: SolanaVerifierInterface)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_solana_verifier.go -package=mocks streamgate/pkg/web3/solana SolanaVerifierInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	solana "github.com/rtcdance/streamgate/pkg/web3/solana"
	gomock "go.uber.org/mock/gomock"
)

// MockSolanaVerifierInterface is a mock of SolanaVerifierInterface interface.
type MockSolanaVerifierInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSolanaVerifierInterfaceMockRecorder
	isgomock struct{}
}

// MockSolanaVerifierInterfaceMockRecorder is the mock recorder for MockSolanaVerifierInterface.
type MockSolanaVerifierInterfaceMockRecorder struct {
	mock *MockSolanaVerifierInterface
}

// NewMockSolanaVerifierInterface creates a new mock instance.
func NewMockSolanaVerifierInterface(ctrl *gomock.Controller) *MockSolanaVerifierInterface {
	mock := &MockSolanaVerifierInterface{ctrl: ctrl}
	mock.recorder = &MockSolanaVerifierInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSolanaVerifierInterface) EXPECT() *MockSolanaVerifierInterfaceMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockSolanaVerifierInterface) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockSolanaVerifierInterfaceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockSolanaVerifierInterface)(nil).Close))
}

// FetchMetaplexMetadata mocks base method.
func (m *MockSolanaVerifierInterface) FetchMetaplexMetadata(ctx context.Context, mintAddress string) (*solana.MetaplexMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchMetaplexMetadata", ctx, mintAddress)
	ret0, _ := ret[0].(*solana.MetaplexMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchMetaplexMetadata indicates an expected call of FetchMetaplexMetadata.
func (mr *MockSolanaVerifierInterfaceMockRecorder) FetchMetaplexMetadata(ctx, mintAddress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchMetaplexMetadata", reflect.TypeOf((*MockSolanaVerifierInterface)(nil).FetchMetaplexMetadata), ctx, mintAddress)
}

// VerifyMetaplexNFTOwnership mocks base method.
func (m *MockSolanaVerifierInterface) VerifyMetaplexNFTOwnership(ctx context.Context, mintAddress, ownerAddress string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyMetaplexNFTOwnership", ctx, mintAddress, ownerAddress)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyMetaplexNFTOwnership indicates an expected call of VerifyMetaplexNFTOwnership.
func (mr *MockSolanaVerifierInterfaceMockRecorder) VerifyMetaplexNFTOwnership(ctx, mintAddress, ownerAddress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyMetaplexNFTOwnership", reflect.TypeOf((*MockSolanaVerifierInterface)(nil).VerifyMetaplexNFTOwnership), ctx, mintAddress, ownerAddress)
}

// VerifyMintAuthority mocks base method.
func (m *MockSolanaVerifierInterface) VerifyMintAuthority(ctx context.Context, mintAddress, authorityAddress string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyMintAuthority", ctx, mintAddress, authorityAddress)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyMintAuthority indicates an expected call of VerifyMintAuthority.
func (mr *MockSolanaVerifierInterfaceMockRecorder) VerifyMintAuthority(ctx, mintAddress, authorityAddress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyMintAuthority", reflect.TypeOf((*MockSolanaVerifierInterface)(nil).VerifyMintAuthority), ctx, mintAddress, authorityAddress)
}

// VerifyTokenAccount mocks base method.
func (m *MockSolanaVerifierInterface) VerifyTokenAccount(ctx context.Context, tokenAccount, ownerAddress string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyTokenAccount", ctx, tokenAccount, ownerAddress)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyTokenAccount indicates an expected call of VerifyTokenAccount.
func (mr *MockSolanaVerifierInterfaceMockRecorder) VerifyTokenAccount(ctx, tokenAccount, ownerAddress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyTokenAccount", reflect.TypeOf((*MockSolanaVerifierInterface)(nil).VerifyTokenAccount), ctx, tokenAccount, ownerAddress)
}
