// Code generated by MockGen. DO NOT EDIT.
// Source: streamgate/pkg/web3 (interfaces: ChainManagerInterface)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_chain_manager.go -package=mocks streamgate/pkg/web3 ChainManagerInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	web3 "github.com/rtcdance/streamgate/pkg/web3"
	solana "github.com/rtcdance/streamgate/pkg/web3/solana"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockChainManagerInterface is a mock of ChainManagerInterface interface.
type MockChainManagerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockChainManagerInterfaceMockRecorder
	isgomock struct{}
}

// MockChainManagerInterfaceMockRecorder is the mock recorder for MockChainManagerInterface.
type MockChainManagerInterfaceMockRecorder struct {
	mock *MockChainManagerInterface
}

// NewMockChainManagerInterface creates a new mock instance.
func NewMockChainManagerInterface(ctrl *gomock.Controller) *MockChainManagerInterface {
	mock := &MockChainManagerInterface{ctrl: ctrl}
	mock.recorder = &MockChainManagerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChainManagerInterface) EXPECT() *MockChainManagerInterfaceMockRecorder {
	return m.recorder
}

// AddChain mocks base method.
func (m *MockChainManagerInterface) AddChain(chainID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddChain", chainID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddChain indicates an expected call of AddChain.
func (mr *MockChainManagerInterfaceMockRecorder) AddChain(chainID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddChain", reflect.TypeOf((*MockChainManagerInterface)(nil).AddChain), chainID)
}

// Close mocks base method.
func (m *MockChainManagerInterface) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockChainManagerInterfaceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockChainManagerInterface)(nil).Close))
}

// GetClient mocks base method.
func (m *MockChainManagerInterface) GetClient(chainID int64) (*web3.ChainClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClient", chainID)
	ret0, _ := ret[0].(*web3.ChainClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClient indicates an expected call of GetClient.
func (mr *MockChainManagerInterfaceMockRecorder) GetClient(chainID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClient", reflect.TypeOf((*MockChainManagerInterface)(nil).GetClient), chainID)
}

// GetMainnetChains mocks base method.
func (m *MockChainManagerInterface) GetMainnetChains() []*web3.ChainConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMainnetChains")
	ret0, _ := ret[0].([]*web3.ChainConfig)
	return ret0
}

// GetMainnetChains indicates an expected call of GetMainnetChains.
func (mr *MockChainManagerInterfaceMockRecorder) GetMainnetChains() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMainnetChains", reflect.TypeOf((*MockChainManagerInterface)(nil).GetMainnetChains))
}

// GetRPCStatuses mocks base method.
func (m *MockChainManagerInterface) GetRPCStatuses() map[int64][]web3.RPCStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRPCStatuses")
	ret0, _ := ret[0].(map[int64][]web3.RPCStatus)
	return ret0
}

// GetRPCStatuses indicates an expected call of GetRPCStatuses.
func (mr *MockChainManagerInterfaceMockRecorder) GetRPCStatuses() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRPCStatuses", reflect.TypeOf((*MockChainManagerInterface)(nil).GetRPCStatuses))
}

// GetSolanaClient mocks base method.
func (m *MockChainManagerInterface) GetSolanaClient(chainID int64) (*solana.SolanaVerifier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSolanaClient", chainID)
	ret0, _ := ret[0].(*solana.SolanaVerifier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSolanaClient indicates an expected call of GetSolanaClient.
func (mr *MockChainManagerInterfaceMockRecorder) GetSolanaClient(chainID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSolanaClient", reflect.TypeOf((*MockChainManagerInterface)(nil).GetSolanaClient), chainID)
}

// GetSupportedChains mocks base method.
func (m *MockChainManagerInterface) GetSupportedChains() []*web3.ChainConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSupportedChains")
	ret0, _ := ret[0].([]*web3.ChainConfig)
	return ret0
}

// GetSupportedChains indicates an expected call of GetSupportedChains.
func (mr *MockChainManagerInterfaceMockRecorder) GetSupportedChains() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSupportedChains", reflect.TypeOf((*MockChainManagerInterface)(nil).GetSupportedChains))
}

// GetTestnetChains mocks base method.
func (m *MockChainManagerInterface) GetTestnetChains() []*web3.ChainConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTestnetChains")
	ret0, _ := ret[0].([]*web3.ChainConfig)
	return ret0
}

// GetTestnetChains indicates an expected call of GetTestnetChains.
func (mr *MockChainManagerInterfaceMockRecorder) GetTestnetChains() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTestnetChains", reflect.TypeOf((*MockChainManagerInterface)(nil).GetTestnetChains))
}

// SetRateLimiter mocks base method.
func (m *MockChainManagerInterface) SetRateLimiter(rl *web3.RPCRateLimiter) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetRateLimiter", rl)
}

// SetRateLimiter indicates an expected call of SetRateLimiter.
func (mr *MockChainManagerInterfaceMockRecorder) SetRateLimiter(rl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRateLimiter", reflect.TypeOf((*MockChainManagerInterface)(nil).SetRateLimiter), rl)
}
