// Code generated by MockGen. DO NOT EDIT.
// Source: streamgate/pkg/web3 (interfaces: HeaderReader)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_header_reader.go -package=mocks streamgate/pkg/web3 HeaderReader
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	big "math/big"
	reflect "reflect"

	ethereum "github.com/ethereum/go-ethereum"
	types "github.com/ethereum/go-ethereum/core/types"
	gomock "go.uber.org/mock/gomock"
)

// MockHeaderReader is a mock of HeaderReader interface.
type MockHeaderReader struct {
	ctrl     *gomock.Controller
	recorder *MockHeaderReaderMockRecorder
	isgomock struct{}
}

// MockHeaderReaderMockRecorder is the mock recorder for MockHeaderReader.
type MockHeaderReaderMockRecorder struct {
	mock *MockHeaderReader
}

// NewMockHeaderReader creates a new mock instance.
func NewMockHeaderReader(ctrl *gomock.Controller) *MockHeaderReader {
	mock := &MockHeaderReader{ctrl: ctrl}
	mock.recorder = &MockHeaderReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHeaderReader) EXPECT() *MockHeaderReaderMockRecorder {
	return m.recorder
}

// HeaderByNumber mocks base method.
func (m *MockHeaderReader) HeaderByNumber(ctx context.Context, number *big.Int) (*types.Header, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HeaderByNumber", ctx, number)
	ret0, _ := ret[0].(*types.Header)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HeaderByNumber indicates an expected call of HeaderByNumber.
func (mr *MockHeaderReaderMockRecorder) HeaderByNumber(ctx, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HeaderByNumber", reflect.TypeOf((*MockHeaderReader)(nil).HeaderByNumber), ctx, number)
}

// SubscribeNewHead mocks base method.
func (m *MockHeaderReader) SubscribeNewHead(ctx context.Context, ch chan<- *types.Header) (ethereum.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeNewHead", ctx, ch)
	ret0, _ := ret[0].(ethereum.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeNewHead indicates an expected call of SubscribeNewHead.
func (mr *MockHeaderReaderMockRecorder) SubscribeNewHead(ctx, ch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeNewHead", reflect.TypeOf((*MockHeaderReader)(nil).SubscribeNewHead), ctx, ch)
}
