apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: streamgate

resources:
  - config/namespace.yaml
  - config/configmap.yaml
  - config/secret.yaml
  - infrastructure/postgres.yaml
  - infrastructure/redis.yaml
  - infrastructure/minio.yaml
  - infrastructure/prometheus.yaml
  - infrastructure/grafana.yaml
  - services/api-gateway.yaml
  - services/transcoder.yaml
  - services/upload.yaml
  - services/streaming.yaml
  - services/metadata.yaml
  - services/cache.yaml
  - services/auth.yaml
  - services/worker.yaml
  - rbac.yaml

commonLabels:
  app.kubernetes.io/name: streamgate
  app.kubernetes.io/instance: streamgate
  app.kubernetes.io/managed-by: kubectl
