// Code generated by MockGen. DO NOT EDIT.
// Source: streamgate/pkg/storage (interfaces: ObjectStorage)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_object_storage.go -package=mocks streamgate/pkg/storage ObjectStorage
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockObjectStorage is a mock of ObjectStorage interface.
type MockObjectStorage struct {
	ctrl     *gomock.Controller
	recorder *MockObjectStorageMockRecorder
	isgomock struct{}
}

// MockObjectStorageMockRecorder is the mock recorder for MockObjectStorage.
type MockObjectStorageMockRecorder struct {
	mock *MockObjectStorage
}

// NewMockObjectStorage creates a new mock instance.
func NewMockObjectStorage(ctrl *gomock.Controller) *MockObjectStorage {
	mock := &MockObjectStorage{ctrl: ctrl}
	mock.recorder = &MockObjectStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObjectStorage) EXPECT() *MockObjectStorageMockRecorder {
	return m.recorder
}

// CreateBucket mocks base method.
func (m *MockObjectStorage) CreateBucket(ctx context.Context, bucket string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBucket", ctx, bucket)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBucket indicates an expected call of CreateBucket.
func (mr *MockObjectStorageMockRecorder) CreateBucket(ctx, bucket any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBucket", reflect.TypeOf((*MockObjectStorage)(nil).CreateBucket), ctx, bucket)
}

// Delete mocks base method.
func (m *MockObjectStorage) Delete(ctx context.Context, bucket, objectName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, bucket, objectName)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockObjectStorageMockRecorder) Delete(ctx, bucket, objectName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockObjectStorage)(nil).Delete), ctx, bucket, objectName)
}

// Download mocks base method.
func (m *MockObjectStorage) Download(ctx context.Context, bucket, objectName string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Download", ctx, bucket, objectName)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Download indicates an expected call of Download.
func (mr *MockObjectStorageMockRecorder) Download(ctx, bucket, objectName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Download", reflect.TypeOf((*MockObjectStorage)(nil).Download), ctx, bucket, objectName)
}

// Exists mocks base method.
func (m *MockObjectStorage) Exists(ctx context.Context, bucket, objectName string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, bucket, objectName)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockObjectStorageMockRecorder) Exists(ctx, bucket, objectName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockObjectStorage)(nil).Exists), ctx, bucket, objectName)
}

// ListObjects mocks base method.
func (m *MockObjectStorage) ListObjects(ctx context.Context, bucket, prefix string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListObjects", ctx, bucket, prefix)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListObjects indicates an expected call of ListObjects.
func (mr *MockObjectStorageMockRecorder) ListObjects(ctx, bucket, prefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListObjects", reflect.TypeOf((*MockObjectStorage)(nil).ListObjects), ctx, bucket, prefix)
}

// Upload mocks base method.
func (m *MockObjectStorage) Upload(ctx context.Context, bucket, objectName string, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", ctx, bucket, objectName, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upload indicates an expected call of Upload.
func (mr *MockObjectStorageMockRecorder) Upload(ctx, bucket, objectName, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockObjectStorage)(nil).Upload), ctx, bucket, objectName, data)
}

// UploadStream mocks base method.
func (m *MockObjectStorage) UploadStream(ctx context.Context, bucket, objectName string, reader io.Reader, size int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadStream", ctx, bucket, objectName, reader, size)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadStream indicates an expected call of UploadStream.
func (mr *MockObjectStorageMockRecorder) UploadStream(ctx, bucket, objectName, reader, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadStream", reflect.TypeOf((*MockObjectStorage)(nil).UploadStream), ctx, bucket, objectName, reader, size)
}

// UploadWithContentType mocks base method.
func (m *MockObjectStorage) UploadWithContentType(ctx context.Context, bucket, objectName string, data []byte, contentType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadWithContentType", ctx, bucket, objectName, data, contentType)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadWithContentType indicates an expected call of UploadWithContentType.
func (mr *MockObjectStorageMockRecorder) UploadWithContentType(ctx, bucket, objectName, data, contentType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadWithContentType", reflect.TypeOf((*MockObjectStorage)(nil).UploadWithContentType), ctx, bucket, objectName, data, contentType)
}
