-- Add missing columns to content table
ALTER TABLE content ADD COLUMN IF NOT EXISTS type VARCHAR(50);
ALTER TABLE content ADD COLUMN IF NOT EXISTS duration INTEGER;
ALTER TABLE content ADD COLUMN IF NOT EXISTS file_size BIGINT;
ALTER TABLE content ADD COLUMN IF NOT EXISTS file_path TEXT;
ALTER TABLE content ADD COLUMN IF NOT EXISTS thumbnail_path TEXT;
ALTER TABLE content ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES users(id);
