-- Add columns to content table
ALTER TABLE contents ADD COLUMN IF NOT EXISTS thumbnail_url VARCHAR(500);
ALTER TABLE contents ADD COLUMN IF NOT EXISTS duration INTEGER;
ALTER TABLE contents ADD COLUMN IF NOT EXISTS size BIGINT;
ALTER TABLE contents ADD COLUMN IF NOT EXISTS owner_id UUID;