-- Add missing columns to nfts table
ALTER TABLE nfts ADD COLUMN IF NOT EXISTS name VARCHAR(255);
ALTER TABLE nfts ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE nfts ADD COLUMN IF NOT EXISTS token_id VARCHAR(100);
ALTER TABLE nfts ADD COLUMN IF NOT EXISTS chain_id INTEGER;
ALTER TABLE nfts ADD COLUMN IF NOT EXISTS chain_name VARCHAR(50);
ALTER TABLE nfts ADD COLUMN IF NOT EXISTS image_url TEXT;
ALTER TABLE nfts ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES users(id);
