ALTER TABLE users ADD COLUMN IF NOT EXISTS role VARCHAR(50) DEFAULT 'user';
ALTER TABLE users ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'active';
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMP;

ALTER TABLE nfts ADD COLUMN IF NOT EXISTS chain_id BIGINT DEFAULT 0;
ALTER TABLE nfts ADD COLUMN IF NOT EXISTS chain_name VARCHAR(100) DEFAULT '';
ALTER TABLE nfts ADD COLUMN IF NOT EXISTS name VARCHAR(255) DEFAULT '';
ALTER TABLE nfts ADD COLUMN IF NOT EXISTS description TEXT DEFAULT '';
ALTER TABLE nfts ADD COLUMN IF NOT EXISTS image_url VARCHAR(500) DEFAULT '';
ALTER TABLE nfts ADD COLUMN IF NOT EXISTS metadata JSONB;
ALTER TABLE nfts ADD COLUMN IF NOT EXISTS verified_at TIMESTAMP;

ALTER TABLE contents ADD COLUMN IF NOT EXISTS file_hash VARCHAR(255) DEFAULT '';
ALTER TABLE contents ADD COLUMN IF NOT EXISTS file_size BIGINT DEFAULT 0;
ALTER TABLE contents ADD COLUMN IF NOT EXISTS tags TEXT[] DEFAULT '{}';
ALTER TABLE contents ADD COLUMN IF NOT EXISTS duration BIGINT;
ALTER TABLE contents ADD COLUMN IF NOT EXISTS thumbnail VARCHAR(500);

ALTER TABLE transactions ADD COLUMN IF NOT EXISTS chain_id BIGINT DEFAULT 0;
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS chain_name VARCHAR(100) DEFAULT '';
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS data JSONB;
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS timestamp BIGINT DEFAULT 0;

ALTER TABLE transcoding_tasks ADD COLUMN IF NOT EXISTS owner_wallet VARCHAR(128) DEFAULT '';

ALTER TABLE streams ADD COLUMN IF NOT EXISTS owner_id VARCHAR(128) DEFAULT '';

ALTER TABLE uploads ADD COLUMN IF NOT EXISTS content_id UUID;

CREATE INDEX IF NOT EXISTS idx_users_role ON users(role);
CREATE INDEX IF NOT EXISTS idx_users_status ON users(status);
CREATE INDEX IF NOT EXISTS idx_nfts_chain ON nfts(chain_id);
CREATE INDEX IF NOT EXISTS idx_streams_owner ON streams(owner_id);
CREATE INDEX IF NOT EXISTS idx_uploads_content ON uploads(content_id);
