apiVersion: v1
kind: Service
metadata:
  name: streamgate-monolith
  labels:
    app: streamgate
    component: monolith
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  - name: grpc
    port: 9090
    targetPort: grpc
    protocol: TCP
  - name: metrics
    port: 9091
    targetPort: metrics
    protocol: TCP
  selector:
    app: streamgate
    component: monolith
  sessionAffinity: None

