// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.1
// source: proto/v1/content.proto

package contentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	common "streamgate/pkg/api/v1/common"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContentRequest) Reset() {
	*x = GetContentRequest{}
	mi := &file_proto_v1_content_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentRequest) ProtoMessage() {}

func (x *GetContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_content_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentRequest.ProtoReflect.Descriptor instead.
func (*GetContentRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_content_proto_rawDescGZIP(), []int{0}
}

func (x *GetContentRequest) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *GetContentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       *Content               `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	StreamingUrls []string               `protobuf:"bytes,2,rep,name=streaming_urls,json=streamingUrls,proto3" json:"streaming_urls,omitempty"`
	Metadata      *common.Metadata       `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContentResponse) Reset() {
	*x = GetContentResponse{}
	mi := &file_proto_v1_content_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentResponse) ProtoMessage() {}

func (x *GetContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_content_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentResponse.ProtoReflect.Descriptor instead.
func (*GetContentResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_content_proto_rawDescGZIP(), []int{1}
}

func (x *GetContentResponse) GetContent() *Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *GetContentResponse) GetStreamingUrls() []string {
	if x != nil {
		return x.StreamingUrls
	}
	return nil
}

func (x *GetContentResponse) GetMetadata() *common.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type VerifyAccessRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContentId       string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WalletAddress   string                 `protobuf:"bytes,3,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	ContractAddress string                 `protobuf:"bytes,4,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	TokenId         string                 `protobuf:"bytes,5,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VerifyAccessRequest) Reset() {
	*x = VerifyAccessRequest{}
	mi := &file_proto_v1_content_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyAccessRequest) ProtoMessage() {}

func (x *VerifyAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_content_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyAccessRequest.ProtoReflect.Descriptor instead.
func (*VerifyAccessRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_content_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyAccessRequest) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *VerifyAccessRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *VerifyAccessRequest) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

func (x *VerifyAccessRequest) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *VerifyAccessRequest) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

type VerifyAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasAccess     bool                   `protobuf:"varint,1,opt,name=has_access,json=hasAccess,proto3" json:"has_access,omitempty"`
	AccessType    string                 `protobuf:"bytes,2,opt,name=access_type,json=accessType,proto3" json:"access_type,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	RequiredNfts  []string               `protobuf:"bytes,4,rep,name=required_nfts,json=requiredNfts,proto3" json:"required_nfts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyAccessResponse) Reset() {
	*x = VerifyAccessResponse{}
	mi := &file_proto_v1_content_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyAccessResponse) ProtoMessage() {}

func (x *VerifyAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_content_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyAccessResponse.ProtoReflect.Descriptor instead.
func (*VerifyAccessResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_content_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyAccessResponse) GetHasAccess() bool {
	if x != nil {
		return x.HasAccess
	}
	return false
}

func (x *VerifyAccessResponse) GetAccessType() string {
	if x != nil {
		return x.AccessType
	}
	return ""
}

func (x *VerifyAccessResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *VerifyAccessResponse) GetRequiredNfts() []string {
	if x != nil {
		return x.RequiredNfts
	}
	return nil
}

type GetTranscodeStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTranscodeStatusRequest) Reset() {
	*x = GetTranscodeStatusRequest{}
	mi := &file_proto_v1_content_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTranscodeStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTranscodeStatusRequest) ProtoMessage() {}

func (x *GetTranscodeStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_content_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTranscodeStatusRequest.ProtoReflect.Descriptor instead.
func (*GetTranscodeStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_content_proto_rawDescGZIP(), []int{4}
}

func (x *GetTranscodeStatusRequest) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

type GetTranscodeStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Progress      int32                  `protobuf:"varint,2,opt,name=progress,proto3" json:"progress,omitempty"`
	Outputs       []*TranscodeOutput     `protobuf:"bytes,3,rep,name=outputs,proto3" json:"outputs,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	StartedAt     int64                  `protobuf:"varint,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   int64                  `protobuf:"varint,6,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTranscodeStatusResponse) Reset() {
	*x = GetTranscodeStatusResponse{}
	mi := &file_proto_v1_content_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTranscodeStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTranscodeStatusResponse) ProtoMessage() {}

func (x *GetTranscodeStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_content_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTranscodeStatusResponse.ProtoReflect.Descriptor instead.
func (*GetTranscodeStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_content_proto_rawDescGZIP(), []int{5}
}

func (x *GetTranscodeStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetTranscodeStatusResponse) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *GetTranscodeStatusResponse) GetOutputs() []*TranscodeOutput {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *GetTranscodeStatusResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *GetTranscodeStatusResponse) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *GetTranscodeStatusResponse) GetCompletedAt() int64 {
	if x != nil {
		return x.CompletedAt
	}
	return 0
}

type ListContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContentRequest) Reset() {
	*x = ListContentRequest{}
	mi := &file_proto_v1_content_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContentRequest) ProtoMessage() {}

func (x *ListContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_content_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContentRequest.ProtoReflect.Descriptor instead.
func (*ListContentRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_content_proto_rawDescGZIP(), []int{6}
}

func (x *ListContentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListContentRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListContentRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListContentRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contents      []*Content             `protobuf:"bytes,1,rep,name=contents,proto3" json:"contents,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContentResponse) Reset() {
	*x = ListContentResponse{}
	mi := &file_proto_v1_content_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContentResponse) ProtoMessage() {}

func (x *ListContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_content_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContentResponse.ProtoReflect.Descriptor instead.
func (*ListContentResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_content_proto_rawDescGZIP(), []int{7}
}

func (x *ListContentResponse) GetContents() []*Content {
	if x != nil {
		return x.Contents
	}
	return nil
}

func (x *ListContentResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListContentResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListContentResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type DeleteContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteContentRequest) Reset() {
	*x = DeleteContentRequest{}
	mi := &file_proto_v1_content_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteContentRequest) ProtoMessage() {}

func (x *DeleteContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_content_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteContentRequest.ProtoReflect.Descriptor instead.
func (*DeleteContentRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_content_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteContentRequest) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *DeleteContentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteContentResponse) Reset() {
	*x = DeleteContentResponse{}
	mi := &file_proto_v1_content_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteContentResponse) ProtoMessage() {}

func (x *DeleteContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_content_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteContentResponse.ProtoReflect.Descriptor instead.
func (*DeleteContentResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_content_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteContentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Content struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,4,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	ThumbnailUrl  string                 `protobuf:"bytes,5,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	Duration      int64                  `protobuf:"varint,6,opt,name=duration,proto3" json:"duration,omitempty"`
	Size          int64                  `protobuf:"varint,7,opt,name=size,proto3" json:"size,omitempty"`
	MimeType      string                 `protobuf:"bytes,8,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Status        string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Tags          []string               `protobuf:"bytes,12,rep,name=tags,proto3" json:"tags,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,13,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Content) Reset() {
	*x = Content{}
	mi := &file_proto_v1_content_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Content) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Content) ProtoMessage() {}

func (x *Content) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_content_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Content.ProtoReflect.Descriptor instead.
func (*Content) Descriptor() ([]byte, []int) {
	return file_proto_v1_content_proto_rawDescGZIP(), []int{10}
}

func (x *Content) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Content) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Content) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Content) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *Content) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *Content) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Content) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Content) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *Content) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Content) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Content) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Content) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Content) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type TranscodeOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Format        string                 `protobuf:"bytes,1,opt,name=format,proto3" json:"format,omitempty"`
	Quality       string                 `protobuf:"bytes,2,opt,name=quality,proto3" json:"quality,omitempty"`
	Width         int32                  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	Bitrate       int32                  `protobuf:"varint,5,opt,name=bitrate,proto3" json:"bitrate,omitempty"`
	Url           string                 `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	Size          int64                  `protobuf:"varint,7,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscodeOutput) Reset() {
	*x = TranscodeOutput{}
	mi := &file_proto_v1_content_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscodeOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscodeOutput) ProtoMessage() {}

func (x *TranscodeOutput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_content_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscodeOutput.ProtoReflect.Descriptor instead.
func (*TranscodeOutput) Descriptor() ([]byte, []int) {
	return file_proto_v1_content_proto_rawDescGZIP(), []int{11}
}

func (x *TranscodeOutput) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *TranscodeOutput) GetQuality() string {
	if x != nil {
		return x.Quality
	}
	return ""
}

func (x *TranscodeOutput) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *TranscodeOutput) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *TranscodeOutput) GetBitrate() int32 {
	if x != nil {
		return x.Bitrate
	}
	return 0
}

func (x *TranscodeOutput) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *TranscodeOutput) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

var File_proto_v1_content_proto protoreflect.FileDescriptor

const file_proto_v1_content_proto_rawDesc = "" +
	"\n" +
	"\x16proto/v1/content.proto\x12\n" +
	"content.v1\x1a\x15proto/v1/common.proto\"K\n" +
	"\x11GetContentRequest\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x9b\x01\n" +
	"\x12GetContentResponse\x12-\n" +
	"\acontent\x18\x01 \x01(\v2\x13.content.v1.ContentR\acontent\x12%\n" +
	"\x0estreaming_urls\x18\x02 \x03(\tR\rstreamingUrls\x12/\n" +
	"\bmetadata\x18\x03 \x01(\v2\x13.common.v1.MetadataR\bmetadata\"\xba\x01\n" +
	"\x13VerifyAccessRequest\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12%\n" +
	"\x0ewallet_address\x18\x03 \x01(\tR\rwalletAddress\x12)\n" +
	"\x10contract_address\x18\x04 \x01(\tR\x0fcontractAddress\x12\x19\n" +
	"\btoken_id\x18\x05 \x01(\tR\atokenId\"\x9a\x01\n" +
	"\x14VerifyAccessResponse\x12\x1d\n" +
	"\n" +
	"has_access\x18\x01 \x01(\bR\thasAccess\x12\x1f\n" +
	"\vaccess_type\x18\x02 \x01(\tR\n" +
	"accessType\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt\x12#\n" +
	"\rrequired_nfts\x18\x04 \x03(\tR\frequiredNfts\":\n" +
	"\x19GetTranscodeStatusRequest\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\"\xee\x01\n" +
	"\x1aGetTranscodeStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1a\n" +
	"\bprogress\x18\x02 \x01(\x05R\bprogress\x125\n" +
	"\aoutputs\x18\x03 \x03(\v2\x1b.content.v1.TranscodeOutputR\aoutputs\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"started_at\x18\x05 \x01(\x03R\tstartedAt\x12!\n" +
	"\fcompleted_at\x18\x06 \x01(\x03R\vcompletedAt\"v\n" +
	"\x12ListContentRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"\x8d\x01\n" +
	"\x13ListContentResponse\x12/\n" +
	"\bcontents\x18\x01 \x03(\v2\x13.content.v1.ContentR\bcontents\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"N\n" +
	"\x14DeleteContentRequest\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"1\n" +
	"\x15DeleteContentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xcc\x03\n" +
	"\aContent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12!\n" +
	"\foriginal_url\x18\x04 \x01(\tR\voriginalUrl\x12#\n" +
	"\rthumbnail_url\x18\x05 \x01(\tR\fthumbnailUrl\x12\x1a\n" +
	"\bduration\x18\x06 \x01(\x03R\bduration\x12\x12\n" +
	"\x04size\x18\a \x01(\x03R\x04size\x12\x1b\n" +
	"\tmime_type\x18\b \x01(\tR\bmimeType\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\x03R\tupdatedAt\x12\x12\n" +
	"\x04tags\x18\f \x03(\tR\x04tags\x12=\n" +
	"\bmetadata\x18\r \x03(\v2!.content.v1.Content.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb1\x01\n" +
	"\x0fTranscodeOutput\x12\x16\n" +
	"\x06format\x18\x01 \x01(\tR\x06format\x12\x18\n" +
	"\aquality\x18\x02 \x01(\tR\aquality\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x05R\x06height\x12\x18\n" +
	"\abitrate\x18\x05 \x01(\x05R\abitrate\x12\x10\n" +
	"\x03url\x18\x06 \x01(\tR\x03url\x12\x12\n" +
	"\x04size\x18\a \x01(\x03R\x04size2\xbb\x03\n" +
	"\x0eContentService\x12K\n" +
	"\n" +
	"GetContent\x12\x1d.content.v1.GetContentRequest\x1a\x1e.content.v1.GetContentResponse\x12Q\n" +
	"\fVerifyAccess\x12\x1f.content.v1.VerifyAccessRequest\x1a .content.v1.VerifyAccessResponse\x12c\n" +
	"\x12GetTranscodeStatus\x12%.content.v1.GetTranscodeStatusRequest\x1a&.content.v1.GetTranscodeStatusResponse\x12N\n" +
	"\vListContent\x12\x1e.content.v1.ListContentRequest\x1a\x1f.content.v1.ListContentResponse\x12T\n" +
	"\rDeleteContent\x12 .content.v1.DeleteContentRequest\x1a!.content.v1.DeleteContentResponseB)Z'streamgate/pkg/api/v1/content;contentv1b\x06proto3"

var (
	file_proto_v1_content_proto_rawDescOnce sync.Once
	file_proto_v1_content_proto_rawDescData []byte
)

func file_proto_v1_content_proto_rawDescGZIP() []byte {
	file_proto_v1_content_proto_rawDescOnce.Do(func() {
		file_proto_v1_content_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_content_proto_rawDesc), len(file_proto_v1_content_proto_rawDesc)))
	})
	return file_proto_v1_content_proto_rawDescData
}

var file_proto_v1_content_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_v1_content_proto_goTypes = []any{
	(*GetContentRequest)(nil),          // 0: content.v1.GetContentRequest
	(*GetContentResponse)(nil),         // 1: content.v1.GetContentResponse
	(*VerifyAccessRequest)(nil),        // 2: content.v1.VerifyAccessRequest
	(*VerifyAccessResponse)(nil),       // 3: content.v1.VerifyAccessResponse
	(*GetTranscodeStatusRequest)(nil),  // 4: content.v1.GetTranscodeStatusRequest
	(*GetTranscodeStatusResponse)(nil), // 5: content.v1.GetTranscodeStatusResponse
	(*ListContentRequest)(nil),         // 6: content.v1.ListContentRequest
	(*ListContentResponse)(nil),        // 7: content.v1.ListContentResponse
	(*DeleteContentRequest)(nil),       // 8: content.v1.DeleteContentRequest
	(*DeleteContentResponse)(nil),      // 9: content.v1.DeleteContentResponse
	(*Content)(nil),                    // 10: content.v1.Content
	(*TranscodeOutput)(nil),            // 11: content.v1.TranscodeOutput
	nil,                                // 12: content.v1.Content.MetadataEntry
	(*common.Metadata)(nil),            // 13: common.v1.Metadata
}
var file_proto_v1_content_proto_depIdxs = []int32{
	10, // 0: content.v1.GetContentResponse.content:type_name -> content.v1.Content
	13, // 1: content.v1.GetContentResponse.metadata:type_name -> common.v1.Metadata
	11, // 2: content.v1.GetTranscodeStatusResponse.outputs:type_name -> content.v1.TranscodeOutput
	10, // 3: content.v1.ListContentResponse.contents:type_name -> content.v1.Content
	12, // 4: content.v1.Content.metadata:type_name -> content.v1.Content.MetadataEntry
	0,  // 5: content.v1.ContentService.GetContent:input_type -> content.v1.GetContentRequest
	2,  // 6: content.v1.ContentService.VerifyAccess:input_type -> content.v1.VerifyAccessRequest
	4,  // 7: content.v1.ContentService.GetTranscodeStatus:input_type -> content.v1.GetTranscodeStatusRequest
	6,  // 8: content.v1.ContentService.ListContent:input_type -> content.v1.ListContentRequest
	8,  // 9: content.v1.ContentService.DeleteContent:input_type -> content.v1.DeleteContentRequest
	1,  // 10: content.v1.ContentService.GetContent:output_type -> content.v1.GetContentResponse
	3,  // 11: content.v1.ContentService.VerifyAccess:output_type -> content.v1.VerifyAccessResponse
	5,  // 12: content.v1.ContentService.GetTranscodeStatus:output_type -> content.v1.GetTranscodeStatusResponse
	7,  // 13: content.v1.ContentService.ListContent:output_type -> content.v1.ListContentResponse
	9,  // 14: content.v1.ContentService.DeleteContent:output_type -> content.v1.DeleteContentResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_v1_content_proto_init() }
func file_proto_v1_content_proto_init() {
	if File_proto_v1_content_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_content_proto_rawDesc), len(file_proto_v1_content_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_content_proto_goTypes,
		DependencyIndexes: file_proto_v1_content_proto_depIdxs,
		MessageInfos:      file_proto_v1_content_proto_msgTypes,
	}.Build()
	File_proto_v1_content_proto = out.File
	file_proto_v1_content_proto_goTypes = nil
	file_proto_v1_content_proto_depIdxs = nil
}
