// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.1
// source: proto/v1/nft.proto

package nftv1

import (
	_ "github.com/rtcdance/streamgate/pkg/api/v1/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VerifyOwnershipRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WalletAddress   string                 `protobuf:"bytes,1,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	ContractAddress string                 `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	TokenId         string                 `protobuf:"bytes,3,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	ChainId         int64                  `protobuf:"varint,4,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	ChainType       string                 `protobuf:"bytes,5,opt,name=chain_type,json=chainType,proto3" json:"chain_type,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VerifyOwnershipRequest) Reset() {
	*x = VerifyOwnershipRequest{}
	mi := &file_proto_v1_nft_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyOwnershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyOwnershipRequest) ProtoMessage() {}

func (x *VerifyOwnershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_nft_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyOwnershipRequest.ProtoReflect.Descriptor instead.
func (*VerifyOwnershipRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_nft_proto_rawDescGZIP(), []int{0}
}

func (x *VerifyOwnershipRequest) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

func (x *VerifyOwnershipRequest) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *VerifyOwnershipRequest) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *VerifyOwnershipRequest) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *VerifyOwnershipRequest) GetChainType() string {
	if x != nil {
		return x.ChainType
	}
	return ""
}

type VerifyOwnershipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnsNft       bool                   `protobuf:"varint,1,opt,name=owns_nft,json=ownsNft,proto3" json:"owns_nft,omitempty"`
	OwnerAddress  string                 `protobuf:"bytes,2,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	Metadata      *NFTMetadata           `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	VerifiedAt    int64                  `protobuf:"varint,4,opt,name=verified_at,json=verifiedAt,proto3" json:"verified_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyOwnershipResponse) Reset() {
	*x = VerifyOwnershipResponse{}
	mi := &file_proto_v1_nft_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyOwnershipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyOwnershipResponse) ProtoMessage() {}

func (x *VerifyOwnershipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_nft_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyOwnershipResponse.ProtoReflect.Descriptor instead.
func (*VerifyOwnershipResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_nft_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyOwnershipResponse) GetOwnsNft() bool {
	if x != nil {
		return x.OwnsNft
	}
	return false
}

func (x *VerifyOwnershipResponse) GetOwnerAddress() string {
	if x != nil {
		return x.OwnerAddress
	}
	return ""
}

func (x *VerifyOwnershipResponse) GetMetadata() *NFTMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *VerifyOwnershipResponse) GetVerifiedAt() int64 {
	if x != nil {
		return x.VerifiedAt
	}
	return 0
}

type GetNFTMetadataRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContractAddress string                 `protobuf:"bytes,1,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	TokenId         string                 `protobuf:"bytes,2,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	ChainId         int64                  `protobuf:"varint,3,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	ChainType       string                 `protobuf:"bytes,4,opt,name=chain_type,json=chainType,proto3" json:"chain_type,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetNFTMetadataRequest) Reset() {
	*x = GetNFTMetadataRequest{}
	mi := &file_proto_v1_nft_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNFTMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNFTMetadataRequest) ProtoMessage() {}

func (x *GetNFTMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_nft_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNFTMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetNFTMetadataRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_nft_proto_rawDescGZIP(), []int{2}
}

func (x *GetNFTMetadataRequest) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *GetNFTMetadataRequest) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *GetNFTMetadataRequest) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *GetNFTMetadataRequest) GetChainType() string {
	if x != nil {
		return x.ChainType
	}
	return ""
}

type GetNFTMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *NFTMetadata           `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNFTMetadataResponse) Reset() {
	*x = GetNFTMetadataResponse{}
	mi := &file_proto_v1_nft_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNFTMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNFTMetadataResponse) ProtoMessage() {}

func (x *GetNFTMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_nft_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNFTMetadataResponse.ProtoReflect.Descriptor instead.
func (*GetNFTMetadataResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_nft_proto_rawDescGZIP(), []int{3}
}

func (x *GetNFTMetadataResponse) GetMetadata() *NFTMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GetNFTMetadataResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type GetNFTBalanceRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WalletAddress   string                 `protobuf:"bytes,1,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	ContractAddress string                 `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	ChainId         int64                  `protobuf:"varint,3,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	ChainType       string                 `protobuf:"bytes,4,opt,name=chain_type,json=chainType,proto3" json:"chain_type,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetNFTBalanceRequest) Reset() {
	*x = GetNFTBalanceRequest{}
	mi := &file_proto_v1_nft_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNFTBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNFTBalanceRequest) ProtoMessage() {}

func (x *GetNFTBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_nft_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNFTBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetNFTBalanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_nft_proto_rawDescGZIP(), []int{4}
}

func (x *GetNFTBalanceRequest) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

func (x *GetNFTBalanceRequest) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *GetNFTBalanceRequest) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *GetNFTBalanceRequest) GetChainType() string {
	if x != nil {
		return x.ChainType
	}
	return ""
}

type GetNFTBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       int64                  `protobuf:"varint,1,opt,name=balance,proto3" json:"balance,omitempty"`
	TokenIds      []string               `protobuf:"bytes,2,rep,name=token_ids,json=tokenIds,proto3" json:"token_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNFTBalanceResponse) Reset() {
	*x = GetNFTBalanceResponse{}
	mi := &file_proto_v1_nft_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNFTBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNFTBalanceResponse) ProtoMessage() {}

func (x *GetNFTBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_nft_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNFTBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetNFTBalanceResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_nft_proto_rawDescGZIP(), []int{5}
}

func (x *GetNFTBalanceResponse) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *GetNFTBalanceResponse) GetTokenIds() []string {
	if x != nil {
		return x.TokenIds
	}
	return nil
}

type ListUserNFTsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletAddress string                 `protobuf:"bytes,1,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	ChainId       int64                  `protobuf:"varint,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	ChainType     string                 `protobuf:"bytes,3,opt,name=chain_type,json=chainType,proto3" json:"chain_type,omitempty"`
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserNFTsRequest) Reset() {
	*x = ListUserNFTsRequest{}
	mi := &file_proto_v1_nft_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserNFTsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserNFTsRequest) ProtoMessage() {}

func (x *ListUserNFTsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_nft_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserNFTsRequest.ProtoReflect.Descriptor instead.
func (*ListUserNFTsRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_nft_proto_rawDescGZIP(), []int{6}
}

func (x *ListUserNFTsRequest) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

func (x *ListUserNFTsRequest) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *ListUserNFTsRequest) GetChainType() string {
	if x != nil {
		return x.ChainType
	}
	return ""
}

func (x *ListUserNFTsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUserNFTsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListUserNFTsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nfts          []*NFTItem             `protobuf:"bytes,1,rep,name=nfts,proto3" json:"nfts,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserNFTsResponse) Reset() {
	*x = ListUserNFTsResponse{}
	mi := &file_proto_v1_nft_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserNFTsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserNFTsResponse) ProtoMessage() {}

func (x *ListUserNFTsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_nft_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserNFTsResponse.ProtoReflect.Descriptor instead.
func (*ListUserNFTsResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_nft_proto_rawDescGZIP(), []int{7}
}

func (x *ListUserNFTsResponse) GetNfts() []*NFTItem {
	if x != nil {
		return x.Nfts
	}
	return nil
}

func (x *ListUserNFTsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListUserNFTsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUserNFTsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetContractInfoRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContractAddress string                 `protobuf:"bytes,1,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	ChainId         int64                  `protobuf:"varint,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	ChainType       string                 `protobuf:"bytes,3,opt,name=chain_type,json=chainType,proto3" json:"chain_type,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetContractInfoRequest) Reset() {
	*x = GetContractInfoRequest{}
	mi := &file_proto_v1_nft_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContractInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContractInfoRequest) ProtoMessage() {}

func (x *GetContractInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_nft_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContractInfoRequest.ProtoReflect.Descriptor instead.
func (*GetContractInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_nft_proto_rawDescGZIP(), []int{8}
}

func (x *GetContractInfoRequest) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *GetContractInfoRequest) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *GetContractInfoRequest) GetChainType() string {
	if x != nil {
		return x.ChainType
	}
	return ""
}

type GetContractInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *ContractInfo          `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContractInfoResponse) Reset() {
	*x = GetContractInfoResponse{}
	mi := &file_proto_v1_nft_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContractInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContractInfoResponse) ProtoMessage() {}

func (x *GetContractInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_nft_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContractInfoResponse.ProtoReflect.Descriptor instead.
func (*GetContractInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_nft_proto_rawDescGZIP(), []int{9}
}

func (x *GetContractInfoResponse) GetInfo() *ContractInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *GetContractInfoResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type NFTMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	AnimationUrl  string                 `protobuf:"bytes,4,opt,name=animation_url,json=animationUrl,proto3" json:"animation_url,omitempty"`
	ExternalUrl   string                 `protobuf:"bytes,5,opt,name=external_url,json=externalUrl,proto3" json:"external_url,omitempty"`
	Attributes    []*NFTAttribute        `protobuf:"bytes,6,rep,name=attributes,proto3" json:"attributes,omitempty"`
	Properties    map[string]string      `protobuf:"bytes,7,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NFTMetadata) Reset() {
	*x = NFTMetadata{}
	mi := &file_proto_v1_nft_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NFTMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NFTMetadata) ProtoMessage() {}

func (x *NFTMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_nft_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NFTMetadata.ProtoReflect.Descriptor instead.
func (*NFTMetadata) Descriptor() ([]byte, []int) {
	return file_proto_v1_nft_proto_rawDescGZIP(), []int{10}
}

func (x *NFTMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NFTMetadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *NFTMetadata) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *NFTMetadata) GetAnimationUrl() string {
	if x != nil {
		return x.AnimationUrl
	}
	return ""
}

func (x *NFTMetadata) GetExternalUrl() string {
	if x != nil {
		return x.ExternalUrl
	}
	return ""
}

func (x *NFTMetadata) GetAttributes() []*NFTAttribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *NFTMetadata) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

type NFTAttribute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraitType     string                 `protobuf:"bytes,1,opt,name=trait_type,json=traitType,proto3" json:"trait_type,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	DisplayType   string                 `protobuf:"bytes,3,opt,name=display_type,json=displayType,proto3" json:"display_type,omitempty"`
	MaxValue      int32                  `protobuf:"varint,4,opt,name=max_value,json=maxValue,proto3" json:"max_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NFTAttribute) Reset() {
	*x = NFTAttribute{}
	mi := &file_proto_v1_nft_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NFTAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NFTAttribute) ProtoMessage() {}

func (x *NFTAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_nft_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NFTAttribute.ProtoReflect.Descriptor instead.
func (*NFTAttribute) Descriptor() ([]byte, []int) {
	return file_proto_v1_nft_proto_rawDescGZIP(), []int{11}
}

func (x *NFTAttribute) GetTraitType() string {
	if x != nil {
		return x.TraitType
	}
	return ""
}

func (x *NFTAttribute) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *NFTAttribute) GetDisplayType() string {
	if x != nil {
		return x.DisplayType
	}
	return ""
}

func (x *NFTAttribute) GetMaxValue() int32 {
	if x != nil {
		return x.MaxValue
	}
	return 0
}

type NFTItem struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContractAddress string                 `protobuf:"bytes,1,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	TokenId         string                 `protobuf:"bytes,2,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	Name            string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Image           string                 `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	Balance         int64                  `protobuf:"varint,5,opt,name=balance,proto3" json:"balance,omitempty"`
	Metadata        *NFTMetadata           `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NFTItem) Reset() {
	*x = NFTItem{}
	mi := &file_proto_v1_nft_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NFTItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NFTItem) ProtoMessage() {}

func (x *NFTItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_nft_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NFTItem.ProtoReflect.Descriptor instead.
func (*NFTItem) Descriptor() ([]byte, []int) {
	return file_proto_v1_nft_proto_rawDescGZIP(), []int{12}
}

func (x *NFTItem) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *NFTItem) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *NFTItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NFTItem) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *NFTItem) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *NFTItem) GetMetadata() *NFTMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ContractInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	ContractType  string                 `protobuf:"bytes,4,opt,name=contract_type,json=contractType,proto3" json:"contract_type,omitempty"`
	ChainId       int64                  `protobuf:"varint,5,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	ChainName     string                 `protobuf:"bytes,6,opt,name=chain_name,json=chainName,proto3" json:"chain_name,omitempty"`
	TotalSupply   int64                  `protobuf:"varint,7,opt,name=total_supply,json=totalSupply,proto3" json:"total_supply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContractInfo) Reset() {
	*x = ContractInfo{}
	mi := &file_proto_v1_nft_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractInfo) ProtoMessage() {}

func (x *ContractInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_nft_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractInfo.ProtoReflect.Descriptor instead.
func (*ContractInfo) Descriptor() ([]byte, []int) {
	return file_proto_v1_nft_proto_rawDescGZIP(), []int{13}
}

func (x *ContractInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ContractInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContractInfo) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *ContractInfo) GetContractType() string {
	if x != nil {
		return x.ContractType
	}
	return ""
}

func (x *ContractInfo) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *ContractInfo) GetChainName() string {
	if x != nil {
		return x.ChainName
	}
	return ""
}

func (x *ContractInfo) GetTotalSupply() int64 {
	if x != nil {
		return x.TotalSupply
	}
	return 0
}

var File_proto_v1_nft_proto protoreflect.FileDescriptor

const file_proto_v1_nft_proto_rawDesc = "" +
	"\n" +
	"\x12proto/v1/nft.proto\x12\x06nft.v1\x1a\x15proto/v1/common.proto\"\xbf\x01\n" +
	"\x16VerifyOwnershipRequest\x12%\n" +
	"\x0ewallet_address\x18\x01 \x01(\tR\rwalletAddress\x12)\n" +
	"\x10contract_address\x18\x02 \x01(\tR\x0fcontractAddress\x12\x19\n" +
	"\btoken_id\x18\x03 \x01(\tR\atokenId\x12\x19\n" +
	"\bchain_id\x18\x04 \x01(\x03R\achainId\x12\x1d\n" +
	"\n" +
	"chain_type\x18\x05 \x01(\tR\tchainType\"\xab\x01\n" +
	"\x17VerifyOwnershipResponse\x12\x19\n" +
	"\bowns_nft\x18\x01 \x01(\bR\aownsNft\x12#\n" +
	"\rowner_address\x18\x02 \x01(\tR\fownerAddress\x12/\n" +
	"\bmetadata\x18\x03 \x01(\v2\x13.nft.v1.NFTMetadataR\bmetadata\x12\x1f\n" +
	"\vverified_at\x18\x04 \x01(\x03R\n" +
	"verifiedAt\"\x97\x01\n" +
	"\x15GetNFTMetadataRequest\x12)\n" +
	"\x10contract_address\x18\x01 \x01(\tR\x0fcontractAddress\x12\x19\n" +
	"\btoken_id\x18\x02 \x01(\tR\atokenId\x12\x19\n" +
	"\bchain_id\x18\x03 \x01(\x03R\achainId\x12\x1d\n" +
	"\n" +
	"chain_type\x18\x04 \x01(\tR\tchainType\"_\n" +
	"\x16GetNFTMetadataResponse\x12/\n" +
	"\bmetadata\x18\x01 \x01(\v2\x13.nft.v1.NFTMetadataR\bmetadata\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"\xa2\x01\n" +
	"\x14GetNFTBalanceRequest\x12%\n" +
	"\x0ewallet_address\x18\x01 \x01(\tR\rwalletAddress\x12)\n" +
	"\x10contract_address\x18\x02 \x01(\tR\x0fcontractAddress\x12\x19\n" +
	"\bchain_id\x18\x03 \x01(\x03R\achainId\x12\x1d\n" +
	"\n" +
	"chain_type\x18\x04 \x01(\tR\tchainType\"N\n" +
	"\x15GetNFTBalanceResponse\x12\x18\n" +
	"\abalance\x18\x01 \x01(\x03R\abalance\x12\x1b\n" +
	"\ttoken_ids\x18\x02 \x03(\tR\btokenIds\"\xa7\x01\n" +
	"\x13ListUserNFTsRequest\x12%\n" +
	"\x0ewallet_address\x18\x01 \x01(\tR\rwalletAddress\x12\x19\n" +
	"\bchain_id\x18\x02 \x01(\x03R\achainId\x12\x1d\n" +
	"\n" +
	"chain_type\x18\x03 \x01(\tR\tchainType\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\"\x82\x01\n" +
	"\x14ListUserNFTsResponse\x12#\n" +
	"\x04nfts\x18\x01 \x03(\v2\x0f.nft.v1.NFTItemR\x04nfts\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"}\n" +
	"\x16GetContractInfoRequest\x12)\n" +
	"\x10contract_address\x18\x01 \x01(\tR\x0fcontractAddress\x12\x19\n" +
	"\bchain_id\x18\x02 \x01(\x03R\achainId\x12\x1d\n" +
	"\n" +
	"chain_type\x18\x03 \x01(\tR\tchainType\"Y\n" +
	"\x17GetContractInfoResponse\x12(\n" +
	"\x04info\x18\x01 \x01(\v2\x14.nft.v1.ContractInfoR\x04info\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"\xdb\x02\n" +
	"\vNFTMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12#\n" +
	"\ranimation_url\x18\x04 \x01(\tR\fanimationUrl\x12!\n" +
	"\fexternal_url\x18\x05 \x01(\tR\vexternalUrl\x124\n" +
	"\n" +
	"attributes\x18\x06 \x03(\v2\x14.nft.v1.NFTAttributeR\n" +
	"attributes\x12C\n" +
	"\n" +
	"properties\x18\a \x03(\v2#.nft.v1.NFTMetadata.PropertiesEntryR\n" +
	"properties\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x83\x01\n" +
	"\fNFTAttribute\x12\x1d\n" +
	"\n" +
	"trait_type\x18\x01 \x01(\tR\ttraitType\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12!\n" +
	"\fdisplay_type\x18\x03 \x01(\tR\vdisplayType\x12\x1b\n" +
	"\tmax_value\x18\x04 \x01(\x05R\bmaxValue\"\xc4\x01\n" +
	"\aNFTItem\x12)\n" +
	"\x10contract_address\x18\x01 \x01(\tR\x0fcontractAddress\x12\x19\n" +
	"\btoken_id\x18\x02 \x01(\tR\atokenId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x04 \x01(\tR\x05image\x12\x18\n" +
	"\abalance\x18\x05 \x01(\x03R\abalance\x12/\n" +
	"\bmetadata\x18\x06 \x01(\v2\x13.nft.v1.NFTMetadataR\bmetadata\"\xd6\x01\n" +
	"\fContractInfo\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12#\n" +
	"\rcontract_type\x18\x04 \x01(\tR\fcontractType\x12\x19\n" +
	"\bchain_id\x18\x05 \x01(\x03R\achainId\x12\x1d\n" +
	"\n" +
	"chain_name\x18\x06 \x01(\tR\tchainName\x12!\n" +
	"\ftotal_supply\x18\a \x01(\x03R\vtotalSupply2\x9e\x03\n" +
	"\n" +
	"NFTService\x12R\n" +
	"\x0fVerifyOwnership\x12\x1e.nft.v1.VerifyOwnershipRequest\x1a\x1f.nft.v1.VerifyOwnershipResponse\x12O\n" +
	"\x0eGetNFTMetadata\x12\x1d.nft.v1.GetNFTMetadataRequest\x1a\x1e.nft.v1.GetNFTMetadataResponse\x12L\n" +
	"\rGetNFTBalance\x12\x1c.nft.v1.GetNFTBalanceRequest\x1a\x1d.nft.v1.GetNFTBalanceResponse\x12I\n" +
	"\fListUserNFTs\x12\x1b.nft.v1.ListUserNFTsRequest\x1a\x1c.nft.v1.ListUserNFTsResponse\x12R\n" +
	"\x0fGetContractInfo\x12\x1e.nft.v1.GetContractInfoRequest\x1a\x1f.nft.v1.GetContractInfoResponseB!Z\x1fstreamgate/pkg/api/v1/nft;nftv1b\x06proto3"

var (
	file_proto_v1_nft_proto_rawDescOnce sync.Once
	file_proto_v1_nft_proto_rawDescData []byte
)

func file_proto_v1_nft_proto_rawDescGZIP() []byte {
	file_proto_v1_nft_proto_rawDescOnce.Do(func() {
		file_proto_v1_nft_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_nft_proto_rawDesc), len(file_proto_v1_nft_proto_rawDesc)))
	})
	return file_proto_v1_nft_proto_rawDescData
}

var file_proto_v1_nft_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_v1_nft_proto_goTypes = []any{
	(*VerifyOwnershipRequest)(nil),  // 0: nft.v1.VerifyOwnershipRequest
	(*VerifyOwnershipResponse)(nil), // 1: nft.v1.VerifyOwnershipResponse
	(*GetNFTMetadataRequest)(nil),   // 2: nft.v1.GetNFTMetadataRequest
	(*GetNFTMetadataResponse)(nil),  // 3: nft.v1.GetNFTMetadataResponse
	(*GetNFTBalanceRequest)(nil),    // 4: nft.v1.GetNFTBalanceRequest
	(*GetNFTBalanceResponse)(nil),   // 5: nft.v1.GetNFTBalanceResponse
	(*ListUserNFTsRequest)(nil),     // 6: nft.v1.ListUserNFTsRequest
	(*ListUserNFTsResponse)(nil),    // 7: nft.v1.ListUserNFTsResponse
	(*GetContractInfoRequest)(nil),  // 8: nft.v1.GetContractInfoRequest
	(*GetContractInfoResponse)(nil), // 9: nft.v1.GetContractInfoResponse
	(*NFTMetadata)(nil),             // 10: nft.v1.NFTMetadata
	(*NFTAttribute)(nil),            // 11: nft.v1.NFTAttribute
	(*NFTItem)(nil),                 // 12: nft.v1.NFTItem
	(*ContractInfo)(nil),            // 13: nft.v1.ContractInfo
	nil,                             // 14: nft.v1.NFTMetadata.PropertiesEntry
}
var file_proto_v1_nft_proto_depIdxs = []int32{
	10, // 0: nft.v1.VerifyOwnershipResponse.metadata:type_name -> nft.v1.NFTMetadata
	10, // 1: nft.v1.GetNFTMetadataResponse.metadata:type_name -> nft.v1.NFTMetadata
	12, // 2: nft.v1.ListUserNFTsResponse.nfts:type_name -> nft.v1.NFTItem
	13, // 3: nft.v1.GetContractInfoResponse.info:type_name -> nft.v1.ContractInfo
	11, // 4: nft.v1.NFTMetadata.attributes:type_name -> nft.v1.NFTAttribute
	14, // 5: nft.v1.NFTMetadata.properties:type_name -> nft.v1.NFTMetadata.PropertiesEntry
	10, // 6: nft.v1.NFTItem.metadata:type_name -> nft.v1.NFTMetadata
	0,  // 7: nft.v1.NFTService.VerifyOwnership:input_type -> nft.v1.VerifyOwnershipRequest
	2,  // 8: nft.v1.NFTService.GetNFTMetadata:input_type -> nft.v1.GetNFTMetadataRequest
	4,  // 9: nft.v1.NFTService.GetNFTBalance:input_type -> nft.v1.GetNFTBalanceRequest
	6,  // 10: nft.v1.NFTService.ListUserNFTs:input_type -> nft.v1.ListUserNFTsRequest
	8,  // 11: nft.v1.NFTService.GetContractInfo:input_type -> nft.v1.GetContractInfoRequest
	1,  // 12: nft.v1.NFTService.VerifyOwnership:output_type -> nft.v1.VerifyOwnershipResponse
	3,  // 13: nft.v1.NFTService.GetNFTMetadata:output_type -> nft.v1.GetNFTMetadataResponse
	5,  // 14: nft.v1.NFTService.GetNFTBalance:output_type -> nft.v1.GetNFTBalanceResponse
	7,  // 15: nft.v1.NFTService.ListUserNFTs:output_type -> nft.v1.ListUserNFTsResponse
	9,  // 16: nft.v1.NFTService.GetContractInfo:output_type -> nft.v1.GetContractInfoResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_v1_nft_proto_init() }
func file_proto_v1_nft_proto_init() {
	if File_proto_v1_nft_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_nft_proto_rawDesc), len(file_proto_v1_nft_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_nft_proto_goTypes,
		DependencyIndexes: file_proto_v1_nft_proto_depIdxs,
		MessageInfos:      file_proto_v1_nft_proto_msgTypes,
	}.Build()
	File_proto_v1_nft_proto = out.File
	file_proto_v1_nft_proto_goTypes = nil
	file_proto_v1_nft_proto_depIdxs = nil
}
