// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.1
// source: proto/v1/streaming.proto

package streamingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	_ "streamgate/pkg/api/v1/common"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStreamURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Format        string                 `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	Quality       string                 `protobuf:"bytes,4,opt,name=quality,proto3" json:"quality,omitempty"`
	Protocol      string                 `protobuf:"bytes,5,opt,name=protocol,proto3" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStreamURLRequest) Reset() {
	*x = GetStreamURLRequest{}
	mi := &file_proto_v1_streaming_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStreamURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStreamURLRequest) ProtoMessage() {}

func (x *GetStreamURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_streaming_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStreamURLRequest.ProtoReflect.Descriptor instead.
func (*GetStreamURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_streaming_proto_rawDescGZIP(), []int{0}
}

func (x *GetStreamURLRequest) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *GetStreamURLRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetStreamURLRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *GetStreamURLRequest) GetQuality() string {
	if x != nil {
		return x.Quality
	}
	return ""
}

func (x *GetStreamURLRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

type GetStreamURLResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	StreamUrl          string                 `protobuf:"bytes,1,opt,name=stream_url,json=streamUrl,proto3" json:"stream_url,omitempty"`
	ManifestUrl        string                 `protobuf:"bytes,2,opt,name=manifest_url,json=manifestUrl,proto3" json:"manifest_url,omitempty"`
	AvailableQualities []*QualityOption       `protobuf:"bytes,3,rep,name=available_qualities,json=availableQualities,proto3" json:"available_qualities,omitempty"`
	ExpiresAt          int64                  `protobuf:"varint,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetStreamURLResponse) Reset() {
	*x = GetStreamURLResponse{}
	mi := &file_proto_v1_streaming_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStreamURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStreamURLResponse) ProtoMessage() {}

func (x *GetStreamURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_streaming_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStreamURLResponse.ProtoReflect.Descriptor instead.
func (*GetStreamURLResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_streaming_proto_rawDescGZIP(), []int{1}
}

func (x *GetStreamURLResponse) GetStreamUrl() string {
	if x != nil {
		return x.StreamUrl
	}
	return ""
}

func (x *GetStreamURLResponse) GetManifestUrl() string {
	if x != nil {
		return x.ManifestUrl
	}
	return ""
}

func (x *GetStreamURLResponse) GetAvailableQualities() []*QualityOption {
	if x != nil {
		return x.AvailableQualities
	}
	return nil
}

func (x *GetStreamURLResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type GetManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManifestRequest) Reset() {
	*x = GetManifestRequest{}
	mi := &file_proto_v1_streaming_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManifestRequest) ProtoMessage() {}

func (x *GetManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_streaming_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManifestRequest.ProtoReflect.Descriptor instead.
func (*GetManifestRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_streaming_proto_rawDescGZIP(), []int{2}
}

func (x *GetManifestRequest) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *GetManifestRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type GetManifestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manifest      string                 `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Segments      []*SegmentInfo         `protobuf:"bytes,3,rep,name=segments,proto3" json:"segments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManifestResponse) Reset() {
	*x = GetManifestResponse{}
	mi := &file_proto_v1_streaming_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManifestResponse) ProtoMessage() {}

func (x *GetManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_streaming_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManifestResponse.ProtoReflect.Descriptor instead.
func (*GetManifestResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_streaming_proto_rawDescGZIP(), []int{3}
}

func (x *GetManifestResponse) GetManifest() string {
	if x != nil {
		return x.Manifest
	}
	return ""
}

func (x *GetManifestResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *GetManifestResponse) GetSegments() []*SegmentInfo {
	if x != nil {
		return x.Segments
	}
	return nil
}

type GetSegmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	SegmentId     string                 `protobuf:"bytes,2,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	Format        string                 `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	Quality       string                 `protobuf:"bytes,4,opt,name=quality,proto3" json:"quality,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSegmentRequest) Reset() {
	*x = GetSegmentRequest{}
	mi := &file_proto_v1_streaming_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSegmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSegmentRequest) ProtoMessage() {}

func (x *GetSegmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_streaming_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSegmentRequest.ProtoReflect.Descriptor instead.
func (*GetSegmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_streaming_proto_rawDescGZIP(), []int{4}
}

func (x *GetSegmentRequest) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *GetSegmentRequest) GetSegmentId() string {
	if x != nil {
		return x.SegmentId
	}
	return ""
}

func (x *GetSegmentRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *GetSegmentRequest) GetQuality() string {
	if x != nil {
		return x.Quality
	}
	return ""
}

type GetSegmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Etag          string                 `protobuf:"bytes,4,opt,name=etag,proto3" json:"etag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSegmentResponse) Reset() {
	*x = GetSegmentResponse{}
	mi := &file_proto_v1_streaming_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSegmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSegmentResponse) ProtoMessage() {}

func (x *GetSegmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_streaming_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSegmentResponse.ProtoReflect.Descriptor instead.
func (*GetSegmentResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_streaming_proto_rawDescGZIP(), []int{5}
}

func (x *GetSegmentResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetSegmentResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *GetSegmentResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetSegmentResponse) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

type StartStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WalletAddress string                 `protobuf:"bytes,3,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartStreamRequest) Reset() {
	*x = StartStreamRequest{}
	mi := &file_proto_v1_streaming_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartStreamRequest) ProtoMessage() {}

func (x *StartStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_streaming_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartStreamRequest.ProtoReflect.Descriptor instead.
func (*StartStreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_streaming_proto_rawDescGZIP(), []int{6}
}

func (x *StartStreamRequest) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *StartStreamRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StartStreamRequest) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

type StartStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	StreamUrl     string                 `protobuf:"bytes,2,opt,name=stream_url,json=streamUrl,proto3" json:"stream_url,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartStreamResponse) Reset() {
	*x = StartStreamResponse{}
	mi := &file_proto_v1_streaming_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartStreamResponse) ProtoMessage() {}

func (x *StartStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_streaming_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartStreamResponse.ProtoReflect.Descriptor instead.
func (*StartStreamResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_streaming_proto_rawDescGZIP(), []int{7}
}

func (x *StartStreamResponse) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *StartStreamResponse) GetStreamUrl() string {
	if x != nil {
		return x.StreamUrl
	}
	return ""
}

func (x *StartStreamResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type StopStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopStreamRequest) Reset() {
	*x = StopStreamRequest{}
	mi := &file_proto_v1_streaming_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopStreamRequest) ProtoMessage() {}

func (x *StopStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_streaming_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopStreamRequest.ProtoReflect.Descriptor instead.
func (*StopStreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_streaming_proto_rawDescGZIP(), []int{8}
}

func (x *StopStreamRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *StopStreamRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type StopStreamResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Duration         int64                  `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
	BytesTransferred int64                  `protobuf:"varint,3,opt,name=bytes_transferred,json=bytesTransferred,proto3" json:"bytes_transferred,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StopStreamResponse) Reset() {
	*x = StopStreamResponse{}
	mi := &file_proto_v1_streaming_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopStreamResponse) ProtoMessage() {}

func (x *StopStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_streaming_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopStreamResponse.ProtoReflect.Descriptor instead.
func (*StopStreamResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_streaming_proto_rawDescGZIP(), []int{9}
}

func (x *StopStreamResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StopStreamResponse) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *StopStreamResponse) GetBytesTransferred() int64 {
	if x != nil {
		return x.BytesTransferred
	}
	return 0
}

type GetStreamStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStreamStatsRequest) Reset() {
	*x = GetStreamStatsRequest{}
	mi := &file_proto_v1_streaming_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStreamStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStreamStatsRequest) ProtoMessage() {}

func (x *GetStreamStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_streaming_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStreamStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStreamStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_streaming_proto_rawDescGZIP(), []int{10}
}

func (x *GetStreamStatsRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

type GetStreamStatsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	StreamId         string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Status           string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	StartedAt        int64                  `protobuf:"varint,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	Duration         int64                  `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"`
	BytesTransferred int64                  `protobuf:"varint,5,opt,name=bytes_transferred,json=bytesTransferred,proto3" json:"bytes_transferred,omitempty"`
	AverageBitrate   float64                `protobuf:"fixed64,6,opt,name=average_bitrate,json=averageBitrate,proto3" json:"average_bitrate,omitempty"`
	BufferEvents     []*BufferEvent         `protobuf:"bytes,7,rep,name=buffer_events,json=bufferEvents,proto3" json:"buffer_events,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetStreamStatsResponse) Reset() {
	*x = GetStreamStatsResponse{}
	mi := &file_proto_v1_streaming_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStreamStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStreamStatsResponse) ProtoMessage() {}

func (x *GetStreamStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_streaming_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStreamStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStreamStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_streaming_proto_rawDescGZIP(), []int{11}
}

func (x *GetStreamStatsResponse) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *GetStreamStatsResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetStreamStatsResponse) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *GetStreamStatsResponse) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *GetStreamStatsResponse) GetBytesTransferred() int64 {
	if x != nil {
		return x.BytesTransferred
	}
	return 0
}

func (x *GetStreamStatsResponse) GetAverageBitrate() float64 {
	if x != nil {
		return x.AverageBitrate
	}
	return 0
}

func (x *GetStreamStatsResponse) GetBufferEvents() []*BufferEvent {
	if x != nil {
		return x.BufferEvents
	}
	return nil
}

type QualityOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quality       string                 `protobuf:"bytes,1,opt,name=quality,proto3" json:"quality,omitempty"`
	Width         int32                  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Bitrate       int32                  `protobuf:"varint,4,opt,name=bitrate,proto3" json:"bitrate,omitempty"`
	Url           string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QualityOption) Reset() {
	*x = QualityOption{}
	mi := &file_proto_v1_streaming_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QualityOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QualityOption) ProtoMessage() {}

func (x *QualityOption) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_streaming_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QualityOption.ProtoReflect.Descriptor instead.
func (*QualityOption) Descriptor() ([]byte, []int) {
	return file_proto_v1_streaming_proto_rawDescGZIP(), []int{12}
}

func (x *QualityOption) GetQuality() string {
	if x != nil {
		return x.Quality
	}
	return ""
}

func (x *QualityOption) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *QualityOption) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *QualityOption) GetBitrate() int32 {
	if x != nil {
		return x.Bitrate
	}
	return 0
}

func (x *QualityOption) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type SegmentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SegmentId     string                 `protobuf:"bytes,1,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	Quality       string                 `protobuf:"bytes,2,opt,name=quality,proto3" json:"quality,omitempty"`
	Duration      int64                  `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Url           string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SegmentInfo) Reset() {
	*x = SegmentInfo{}
	mi := &file_proto_v1_streaming_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SegmentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentInfo) ProtoMessage() {}

func (x *SegmentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_streaming_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentInfo.ProtoReflect.Descriptor instead.
func (*SegmentInfo) Descriptor() ([]byte, []int) {
	return file_proto_v1_streaming_proto_rawDescGZIP(), []int{13}
}

func (x *SegmentInfo) GetSegmentId() string {
	if x != nil {
		return x.SegmentId
	}
	return ""
}

func (x *SegmentInfo) GetQuality() string {
	if x != nil {
		return x.Quality
	}
	return ""
}

func (x *SegmentInfo) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *SegmentInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *SegmentInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type BufferEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	BufferLength  float64                `protobuf:"fixed64,3,opt,name=buffer_length,json=bufferLength,proto3" json:"buffer_length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BufferEvent) Reset() {
	*x = BufferEvent{}
	mi := &file_proto_v1_streaming_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BufferEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BufferEvent) ProtoMessage() {}

func (x *BufferEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_streaming_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BufferEvent.ProtoReflect.Descriptor instead.
func (*BufferEvent) Descriptor() ([]byte, []int) {
	return file_proto_v1_streaming_proto_rawDescGZIP(), []int{14}
}

func (x *BufferEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BufferEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *BufferEvent) GetBufferLength() float64 {
	if x != nil {
		return x.BufferLength
	}
	return 0
}

var File_proto_v1_streaming_proto protoreflect.FileDescriptor

const file_proto_v1_streaming_proto_rawDesc = "" +
	"\n" +
	"\x18proto/v1/streaming.proto\x12\fstreaming.v1\x1a\x15proto/v1/common.proto\"\x9b\x01\n" +
	"\x13GetStreamURLRequest\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12\x18\n" +
	"\aquality\x18\x04 \x01(\tR\aquality\x12\x1a\n" +
	"\bprotocol\x18\x05 \x01(\tR\bprotocol\"\xc5\x01\n" +
	"\x14GetStreamURLResponse\x12\x1d\n" +
	"\n" +
	"stream_url\x18\x01 \x01(\tR\tstreamUrl\x12!\n" +
	"\fmanifest_url\x18\x02 \x01(\tR\vmanifestUrl\x12L\n" +
	"\x13available_qualities\x18\x03 \x03(\v2\x1b.streaming.v1.QualityOptionR\x12availableQualities\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\x03R\texpiresAt\"K\n" +
	"\x12GetManifestRequest\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\"\x8b\x01\n" +
	"\x13GetManifestResponse\x12\x1a\n" +
	"\bmanifest\x18\x01 \x01(\tR\bmanifest\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x125\n" +
	"\bsegments\x18\x03 \x03(\v2\x19.streaming.v1.SegmentInfoR\bsegments\"\x83\x01\n" +
	"\x11GetSegmentRequest\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\x12\x1d\n" +
	"\n" +
	"segment_id\x18\x02 \x01(\tR\tsegmentId\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12\x18\n" +
	"\aquality\x18\x04 \x01(\tR\aquality\"s\n" +
	"\x12GetSegmentResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x12\n" +
	"\x04etag\x18\x04 \x01(\tR\x04etag\"s\n" +
	"\x12StartStreamRequest\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12%\n" +
	"\x0ewallet_address\x18\x03 \x01(\tR\rwalletAddress\"p\n" +
	"\x13StartStreamResponse\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12\x1d\n" +
	"\n" +
	"stream_url\x18\x02 \x01(\tR\tstreamUrl\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt\"I\n" +
	"\x11StopStreamRequest\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"w\n" +
	"\x12StopStreamResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1a\n" +
	"\bduration\x18\x02 \x01(\x03R\bduration\x12+\n" +
	"\x11bytes_transferred\x18\x03 \x01(\x03R\x10bytesTransferred\"4\n" +
	"\x15GetStreamStatsRequest\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\"\x9e\x02\n" +
	"\x16GetStreamStatsResponse\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"started_at\x18\x03 \x01(\x03R\tstartedAt\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\x03R\bduration\x12+\n" +
	"\x11bytes_transferred\x18\x05 \x01(\x03R\x10bytesTransferred\x12'\n" +
	"\x0faverage_bitrate\x18\x06 \x01(\x01R\x0eaverageBitrate\x12>\n" +
	"\rbuffer_events\x18\a \x03(\v2\x19.streaming.v1.BufferEventR\fbufferEvents\"\x83\x01\n" +
	"\rQualityOption\x12\x18\n" +
	"\aquality\x18\x01 \x01(\tR\aquality\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\x12\x18\n" +
	"\abitrate\x18\x04 \x01(\x05R\abitrate\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\"\x88\x01\n" +
	"\vSegmentInfo\x12\x1d\n" +
	"\n" +
	"segment_id\x18\x01 \x01(\tR\tsegmentId\x12\x18\n" +
	"\aquality\x18\x02 \x01(\tR\aquality\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\x03R\bduration\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\"o\n" +
	"\vBufferEvent\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12#\n" +
	"\rbuffer_length\x18\x03 \x01(\x01R\fbufferLength2\x90\x04\n" +
	"\x10StreamingService\x12U\n" +
	"\fGetStreamURL\x12!.streaming.v1.GetStreamURLRequest\x1a\".streaming.v1.GetStreamURLResponse\x12R\n" +
	"\vGetManifest\x12 .streaming.v1.GetManifestRequest\x1a!.streaming.v1.GetManifestResponse\x12O\n" +
	"\n" +
	"GetSegment\x12\x1f.streaming.v1.GetSegmentRequest\x1a .streaming.v1.GetSegmentResponse\x12R\n" +
	"\vStartStream\x12 .streaming.v1.StartStreamRequest\x1a!.streaming.v1.StartStreamResponse\x12O\n" +
	"\n" +
	"StopStream\x12\x1f.streaming.v1.StopStreamRequest\x1a .streaming.v1.StopStreamResponse\x12[\n" +
	"\x0eGetStreamStats\x12#.streaming.v1.GetStreamStatsRequest\x1a$.streaming.v1.GetStreamStatsResponseB-Z+streamgate/pkg/api/v1/streaming;streamingv1b\x06proto3"

var (
	file_proto_v1_streaming_proto_rawDescOnce sync.Once
	file_proto_v1_streaming_proto_rawDescData []byte
)

func file_proto_v1_streaming_proto_rawDescGZIP() []byte {
	file_proto_v1_streaming_proto_rawDescOnce.Do(func() {
		file_proto_v1_streaming_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_streaming_proto_rawDesc), len(file_proto_v1_streaming_proto_rawDesc)))
	})
	return file_proto_v1_streaming_proto_rawDescData
}

var file_proto_v1_streaming_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_v1_streaming_proto_goTypes = []any{
	(*GetStreamURLRequest)(nil),    // 0: streaming.v1.GetStreamURLRequest
	(*GetStreamURLResponse)(nil),   // 1: streaming.v1.GetStreamURLResponse
	(*GetManifestRequest)(nil),     // 2: streaming.v1.GetManifestRequest
	(*GetManifestResponse)(nil),    // 3: streaming.v1.GetManifestResponse
	(*GetSegmentRequest)(nil),      // 4: streaming.v1.GetSegmentRequest
	(*GetSegmentResponse)(nil),     // 5: streaming.v1.GetSegmentResponse
	(*StartStreamRequest)(nil),     // 6: streaming.v1.StartStreamRequest
	(*StartStreamResponse)(nil),    // 7: streaming.v1.StartStreamResponse
	(*StopStreamRequest)(nil),      // 8: streaming.v1.StopStreamRequest
	(*StopStreamResponse)(nil),     // 9: streaming.v1.StopStreamResponse
	(*GetStreamStatsRequest)(nil),  // 10: streaming.v1.GetStreamStatsRequest
	(*GetStreamStatsResponse)(nil), // 11: streaming.v1.GetStreamStatsResponse
	(*QualityOption)(nil),          // 12: streaming.v1.QualityOption
	(*SegmentInfo)(nil),            // 13: streaming.v1.SegmentInfo
	(*BufferEvent)(nil),            // 14: streaming.v1.BufferEvent
}
var file_proto_v1_streaming_proto_depIdxs = []int32{
	12, // 0: streaming.v1.GetStreamURLResponse.available_qualities:type_name -> streaming.v1.QualityOption
	13, // 1: streaming.v1.GetManifestResponse.segments:type_name -> streaming.v1.SegmentInfo
	14, // 2: streaming.v1.GetStreamStatsResponse.buffer_events:type_name -> streaming.v1.BufferEvent
	0,  // 3: streaming.v1.StreamingService.GetStreamURL:input_type -> streaming.v1.GetStreamURLRequest
	2,  // 4: streaming.v1.StreamingService.GetManifest:input_type -> streaming.v1.GetManifestRequest
	4,  // 5: streaming.v1.StreamingService.GetSegment:input_type -> streaming.v1.GetSegmentRequest
	6,  // 6: streaming.v1.StreamingService.StartStream:input_type -> streaming.v1.StartStreamRequest
	8,  // 7: streaming.v1.StreamingService.StopStream:input_type -> streaming.v1.StopStreamRequest
	10, // 8: streaming.v1.StreamingService.GetStreamStats:input_type -> streaming.v1.GetStreamStatsRequest
	1,  // 9: streaming.v1.StreamingService.GetStreamURL:output_type -> streaming.v1.GetStreamURLResponse
	3,  // 10: streaming.v1.StreamingService.GetManifest:output_type -> streaming.v1.GetManifestResponse
	5,  // 11: streaming.v1.StreamingService.GetSegment:output_type -> streaming.v1.GetSegmentResponse
	7,  // 12: streaming.v1.StreamingService.StartStream:output_type -> streaming.v1.StartStreamResponse
	9,  // 13: streaming.v1.StreamingService.StopStream:output_type -> streaming.v1.StopStreamResponse
	11, // 14: streaming.v1.StreamingService.GetStreamStats:output_type -> streaming.v1.GetStreamStatsResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_v1_streaming_proto_init() }
func file_proto_v1_streaming_proto_init() {
	if File_proto_v1_streaming_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_streaming_proto_rawDesc), len(file_proto_v1_streaming_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_streaming_proto_goTypes,
		DependencyIndexes: file_proto_v1_streaming_proto_depIdxs,
		MessageInfos:      file_proto_v1_streaming_proto_msgTypes,
	}.Build()
	File_proto_v1_streaming_proto = out.File
	file_proto_v1_streaming_proto_goTypes = nil
	file_proto_v1_streaming_proto_depIdxs = nil
}
