// Code generated by MockGen. DO NOT EDIT.
// Source: streamgate/pkg/cachetypes (interfaces: CacheBackend)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_cache_backend.go -package=mocks streamgate/pkg/cachetypes CacheBackend
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockCacheBackend is a mock of CacheBackend interface.
type MockCacheBackend struct {
	ctrl     *gomock.Controller
	recorder *MockCacheBackendMockRecorder
	isgomock struct{}
}

// MockCacheBackendMockRecorder is the mock recorder for MockCacheBackend.
type MockCacheBackendMockRecorder struct {
	mock *MockCacheBackend
}

// NewMockCacheBackend creates a new mock instance.
func NewMockCacheBackend(ctrl *gomock.Controller) *MockCacheBackend {
	mock := &MockCacheBackend{ctrl: ctrl}
	mock.recorder = &MockCacheBackendMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheBackend) EXPECT() *MockCacheBackendMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockCacheBackend) Delete(key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCacheBackendMockRecorder) Delete(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCacheBackend)(nil).Delete), key)
}

// Get mocks base method.
func (m *MockCacheBackend) Get(key string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCacheBackendMockRecorder) Get(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCacheBackend)(nil).Get), key)
}

// Set mocks base method.
func (m *MockCacheBackend) Set(key string, value any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockCacheBackendMockRecorder) Set(key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockCacheBackend)(nil).Set), key, value)
}

// SetWithExpiration mocks base method.
func (m *MockCacheBackend) SetWithExpiration(key string, value any, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetWithExpiration", key, value, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetWithExpiration indicates an expected call of SetWithExpiration.
func (mr *MockCacheBackendMockRecorder) SetWithExpiration(key, value, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetWithExpiration", reflect.TypeOf((*MockCacheBackend)(nil).SetWithExpiration), key, value, ttl)
}
