apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: streamgate

resources:
  - ../../base

commonLabels:
  environment: prod

replicas:
  - name: api-gateway
    count: 3
  - name: transcoder
    count: 2
  - name: upload
    count: 2
  - name: streaming
    count: 4
  - name: metadata
    count: 2
  - name: cache
    count: 2
  - name: auth
    count: 3
  - name: worker
    count: 3
  - name: streamgate-monolith
    count: 5

images:
  - name: streamgate/monolith
    newTag: latest
  - name: streamgate
    newTag: latest

configMapGenerator:
  - name: streamgate-config
    behavior: merge
    literals:
      - ENVIRONMENT=production
